import type { Course } from "./_schema";

export const becWorkplaceCourse: Course = {
  slug: "bec-pracovisko-fake-ceo",
  title: `BEC: keď ti „CEO" napíše súrne preveď 50 000 EUR`,
  tagline:
    "Business Email Compromise (podvod cez kompromitovaný firemný e-mail) je najdrahšia forma firemného phishingu (podvodné vylákanie prihlasovacích či platobných údajov): 5 typov + 6 procesných obrán pre účtovníkov a HR.",
  category: "obecne",
  difficulty: "pokročilý",
  estimatedMinutes: 13,
  heroEmoji: "🏢",
  publishedAt: "2026-04-26",
  updatedAt: "2026-04-26",
  sections: [
    {
      kind: "embed",
      heading: "Pozri si na úvod: falošní dodávatelia a riaditelia",
      audio: {
        provider: "youtube",
        url: "https://www.youtube.com/watch?v=x1IvCIWcprk",
        title: "Pozor na falošných dodávateľov či riaditeľov firiem",
        sourceName: "Tatra banka",
        sourceUrl: "https://www.youtube.com/watch?v=x1IvCIWcprk",
        description:
          "Osvetové video Tatra banky o podvodoch typu BEC (falošný riaditeľ/dodávateľ). Názorná ukážka.",
      },
    },
    {
      kind: "intro",
      heading: `BEC = jeden e-mail, 50 000 EUR preč`,
      body: `Business Email Compromise cieli na účtovníkov, asistentov, finančných manažérov v SK firmách. Útočník 2 – 4 týždne sleduje firemnú komunikáciu (cez jeden phishnutý účet alebo verejné LinkedIn dáta), naučí sa štýl CEO/CFO a potom v správnu chvíľu (pred dovolenkou, pri uzávierke) pošle „súrnu" žiadosť o prevod. Priemerná škoda na incident v EÚ podľa Europolu presahuje 50 000 EUR. Prevencia je 90 % o procese, 10 % o technike.`,
    },
    {
      kind: "example",
      heading: `Typ #1 — fake CEO ("som na meeting-u, urgentne preveď")`,
      visual: {
        kind: "email",
        from: "Peter Novák (CEO)",
        fromEmail: "peter.novak@firma-sk.co",
        subject: "Súrne — potrebujem prevod, som na klientskom meetingu",
        body: `Mária, som teraz na zákazníckom meetingu v Mníchove a nemôžem volať. Potrebujem urgentne prevodom poslať 47 800 EUR na účet nového dodávateľa. IBAN: DE89 3704 0044 0532 0130 00. Svif: COBADEFFXXX. Pošli potvrdenie po vykonaní, ďakujem.`,
      },
      commentary: `Klasický CEO Fraud. Doména 'firma-sk.co' (skutočná je 'firma.sk'). Štýl je natrénovaný — útočník čítal váš e-mailový archív týždne. „Som na meetingu, nemôžem volať" je obrana proti out-of-band verifikácii. Tento jeden e-mail je najdrahší v EÚ.`,
    },
    {
      kind: "example",
      heading: `Typ #2 — fake CFO mení bankové údaje dodávateľa`,
      visual: {
        kind: "email",
        from: "Jana Horváthová (CFO)",
        fromEmail: "jana.horvathova@firma.sk",
        subject: "Aktualizácia bankového účtu pre dodávateľa MetalTech",
        body: `Mária, MetalTech mi práve volal — menia bankový účet kvôli akvizícii. Nový IBAN pre faktúry: SK35 1100 0000 0099 8877 6655. Použi ho na faktúru #2024-1187 (12 400 EUR), ktorú máš dnes splatnú. Potvrdím e-mailom keď bude účet aktívny.`,
      },
      commentary: `Útočník phishol jeden interný účet (CFO) alebo spoofuje (podvrhnutie identity odosielateľa) doménu. Cieľ: prevod existujúcej legitímnej faktúry na ich účet. Túto schému zachytí len telefonický callback dodávateľovi — žiadny e-mail nestačí, lebo aj „potvrdenie" môže prísť z toho istého kompromitovaného účtu.`,
    },
    {
      kind: "example",
      heading: `Typ #3 — fake právnik („dôverné M&A, žiadne otázky")`,
      visual: {
        kind: "email",
        from: "Dr. Marek Polák, Polák & Partners",
        fromEmail: "marek.polak@polak-partners-legal.com",
        subject: "Dôverné — akvizícia, prevod escrow",
        body: `Mária, vaša spoločnosť je v procese akvizície, ktorú náš úrad sprostredkováva. Pre právnu istotu potrebujeme escrow prevod 78 000 EUR na náš účet do 17:00 dnes. CEO Peter Novák to odsouhlasil ústne, ale kvôli regulačnému embargu nemôže komunikovať písomne. Poznáte nasledujúcich 48 hodín ako confidentiality period — žiadne otázky kolegom.`,
      },
      commentary: `Pridáva autoritu („právnik", „M&A") a izoláciu („nehovor s kolegami"). „Embargo" je psychologický trik — útočník vie, že callback by ho odhalil. Žiadny advokát nedonúti účtovníka k prevodu bez podpísanej zmluvy a bez možnosti overiť ho s CEO.`,
    },
    {
      kind: "example",
      heading: `Typ #4 — phishing (podvodné vylákanie údajov) CEO účtu cez Microsoft 365 spoof`,
      visual: {
        kind: "email",
        from: "Microsoft 365 Security",
        fromEmail: "no-reply@m365-account-security.com",
        subject: "Vaše heslo Microsoft 365 vyprší o 24h — okamžitá akcia potrebná",
        body: `CEO/admin: vaše heslo k Microsoft 365 účtu vyprší o 24 hodín. Aby ste zachovali prístup k Outlook, OneDrive a Teams, potvrďte súčasné heslo cez nižšie uvedený odkaz.`,
        cta: "Zachovať prístup",
      },
      commentary: `Toto je vstupný vektor pre BEC. Útočník phishne CEO heslo, prihlási sa do Outlooku, číta komunikáciu, naučí sa štýl. Až potom (po týždňoch) pošle z reálneho CEO mailboxu falošnú žiadosť o prevod. To je ten najnebezpečnejší typ — žiadny spoofing, e-mail je z naozaj firemnej domény.`,
    },
    {
      kind: "example",
      heading: `Typ #5 — payroll diversion (zamestnanec mení svoj výplatný účet)`,
      visual: {
        kind: "email",
        from: "Tomáš Krajči",
        fromEmail: "tomas.krajci@firma-sk.co",
        subject: "Zmena bankového účtu pre výplatu",
        body: `Mária, prosím zmeň môj výplatný účet pre nasledujúcu výplatu. Otvoril som si nový účet v Tatra banke. IBAN: SK11 1100 0000 0066 5544 3322. Ďakujem, Tomáš`,
      },
      commentary: `Útočník phishne zamestnanca alebo spoofuje doménu, požiada o presmerovanie výplaty. Účtovníctvo to často vykoná bez overenia (zdá sa neškodné). Skutočný zamestnanec zistí, až keď výplata nepríde. Ochrana: každú zmenu výplatného účtu overiť osobne alebo telefonicky na predchádzajúce známe číslo.`,
    },
    {
      kind: "redflags",
      heading: "Indície BEC v príchodzom e-maile",
      flags: [
        `Doména odosielateľa je „skoro" správna — 'firma-sk.co' namiesto 'firma.sk'.`,
        `Naliehanie na čas — „dnes do 17:00", „pred odchodom na dovolenku".`,
        `Zákaz overenia — „som na meetingu, nemôžem volať", „dôverné, neukáž kolegom".`,
        `Žiadosť o prevod na nový (predtým nepoužitý) účet.`,
        `Zmena bankového účtu existujúceho dodávateľa, len cez e-mail.`,
        `Štýl odosielateľa sa „skoro" hodí, ale niečo nesedí (vykanie, formálnosť).`,
        `Žiadosť o platbu mimo bežného workflow (Excel-faktúra, krypto, gift cards).`,
        `Reply-To pole sa líši od From poľa.`,
      ],
    },
    {
      kind: "do_dont",
      heading: "Procesné obrany (90 % BEC zachytíš procesom, nie technikou)",
      do: [
        `Two-person rule pre prevody nad 5 000 EUR — vždy schvaľujú dvaja ľudia.`,
        `Out-of-band verifikácia — pri každej žiadosti o prevod zavolaj CEO/CFO na známe číslo (nie z e-mailu).`,
        `Zmena bankového účtu dodávateľa — vždy potvrdiť osobne / telefonicky na pred-existujúce číslo.`,
        `Zmena výplatného účtu zamestnanca — vždy overenie cez HR, ideálne osobne.`,
        `2FA (dvojfaktorové overenie) na všetkých Microsoft 365 / Google Workspace účtoch (najmä management).`,
        `Pravidelný BEC training pre účtovníctvo — phishing simulácie 2x ročne.`,
      ],
      dont: [
        `Nevykonať prevod len na základe e-mailu, bez druhej verifikácie.`,
        `Neignorovať „skoro správnu" doménu — vždy preveriť písmeno po písmene.`,
        `Nepoužiť kontaktné číslo z e-mailu na callback — vždy z firemného adresára.`,
        `Neprijímať „embargo" / „dôvernosť" ako dôvod nepovedať to nikomu.`,
        `Neodkladaj procesné kontroly „lebo CEO sa hnevá, že to dlho trvá".`,
      ],
    },
    {
      kind: "checklist",
      heading: "Pred-prevodový checklist (vytlač a polož na stôl účtovníčke)",
      items: [
        { good: true, text: `Doménu odosielateľa som skontroloval/a znak po znaku.` },
        { good: true, text: `CEO/CFO som zavolal/a na známe číslo a verifikoval/a žiadosť.` },
        { good: true, text: `Pri novom IBAN som zavolal/a dodávateľovi na pred-existujúce číslo.` },
        { good: true, text: `Pri prevode nad 5 000 EUR mám second approval od kolegu.` },
        { good: false, text: `„Súrne, do hodiny" — ZASTAV, over znova.` },
        { good: false, text: `„Nehovor o tom kolegom, dôverné" — ZASTAV, over.` },
        { good: false, text: `Komunikácia ide len cez e-mail, žiadny telefonický kontakt.` },
      ],
    },
    {
      kind: "scenario",
      heading: "Reálny scenár — piatok 16:30, pred dovolenkou",
      story: `Si účtovníčka v 30-osobovej firme. CEO Peter Novák ide o hodinu na 2-týždňovú dovolenku. Príde e-mail z 'peter.novak@firma-sk.co': „Mária, súrne preveď 47 800 EUR na nového dodávateľa pred mojím odchodom. IBAN posielam v ďalšej správe. Žiadam ťa, aby si to spravila ešte dnes — ďakujem."`,
      right_action: `Zavoláš Petrovi na jeho mobilné číslo (z firemného adresára, nie z e-mailu). Ak nedvíha, napíšeš na osobný WhatsApp / Signal. Aj keby to spôsobilo 30-minútové zdržanie — Peter to ocení viac ako stratu 47 800 EUR. Doménu 'firma-sk.co' po druhom pohľade vidíš — vy ste '.sk', nie '.co'. To je ten varovný signál.`,
    },
  ],
  sources: [
    { label: `Europol — BEC report (EÚ priemerná škoda)`, url: "https://www.europol.europa.eu/" },
    { label: `NCKB — sociálne inžinierstvo na pracovisku`, url: "https://www.sk-cert.sk/" },
    { label: `Microsoft — Identifying BEC patterns`, url: "https://learn.microsoft.com/" },
  ],
};
