import type { Course } from "./_schema";

export const emailPhishingCourse: Course = {
  slug: "email-phishing",
  title: "Email phishing — ako rozoznať podvodný e-mail",
  tagline:
    "Falošná banka, falošný Microsoft, falošný šéf: 6 typických vzorov a 30-sekundový checklist, ktorým ich odhalíš.",
  category: "email",
  difficulty: "začiatočník",
  estimatedMinutes: 9,
  heroEmoji: "✉️",
  relatedQuestionsCategory: "phishing",
  publishedAt: "2026-04-26",
  updatedAt: "2026-04-26",
  sections: [
    {
      kind: "intro",
      heading: "Email je stále útok č. 1",
      body: `Aj keď SMS vedie v rýchlosti, e-mail je stále hlavný kanál pre cielené phishingové (podvodné vylákanie prihlasovacích či platobných údajov) útoky. Útočník má v ňom miesto na presvedčivý dizajn, falošné logá a kvalitne preložený text. Cieľ je rovnaký: dostať ťa na falošnú stránku alebo aby si stiahol prílohu.`,
    },
    {
      kind: "example",
      heading: `Vzor #1 — „Slovenská sporiteľňa" o blokovaní účtu`,
      visual: {
        kind: "email",
        from: "Slovenská sporiteľňa",
        fromEmail: "no-reply@slsp-bezpecnost.online",
        subject: "Bezpečnostné upozornenie — overte sa do 24 hodín",
        body: `Vážený klient, na vašom účte boli zaznamenané neobvyklé pohyby. Ak sa do 24 hodín nepriahlasite cez nižšie uvedený odkaz, váš prístup do internet bankingu bude pozastavený.`,
        cta: "Overiť účet",
      },
      commentary: `Doména odosielateľa slsp-bezpecnost.online — Slovenská sporiteľňa píše z @slsp.sk, nie z náhodne registrovanej .online. „Overte sa do 24 hodín" je pavlovovský reflex na strach. Žiadna banka takto nekomunikuje.`,
    },
    {
      kind: "example",
      heading: `Vzor #2 — „Microsoft 365" o vypršaní hesla`,
      visual: {
        kind: "email",
        from: "Microsoft Account Team",
        fromEmail: "security@microsoft-update-services.com",
        subject: "Vaše heslo vyprší o 24 hodín — okamžite ho obnovte",
        body: `Vaše heslo k Microsoft 365 účtu vyprší o 24 hodín. Aby ste predišli prerušeniu prístupu k pošte a OneDrive, kliknite a obnovte heslo.`,
        cta: "Obnoviť heslo",
      },
      commentary: `Microsoft komunikuje výhradne z @microsoft.com a @account.microsoft.com. Doména microsoft-update-services.com je registrovaná pred mesiacom. „Vyprší o 24 hodín" je klasická naliehavosť.`,
    },
    {
      kind: "example",
      heading: `Vzor #3 — „CEO/šéf" žiada urgentnú platbu (BEC)`,
      visual: {
        kind: "email",
        from: "Peter Novák (CEO)",
        fromEmail: "peter.novak@firma-sk.co",
        subject: "Urgentne — potrebujem prevod, som na meeting-u",
        body: `Ahoj, som teraz na zákazníckom meetingu a nemôžem volať. Potrebujem urgentne prevodom poslať 7 800 EUR na účet dodávateľa, číslo IBAN: SK35 ... Pošli mi potvrdenie, ďakujem.`,
      },
      commentary: `Tzv. Business Email Compromise (podvod cez kompromitovaný firemný e-mail), skrátene BEC. Útočník si spravil doménu firma-sk.co (skutočná je firma.sk). Píše v štýle CEO, vyvíja tlak. Žiadny šéf nepýta urgentnú platbu cez e-mail bez verifikácie. Vždy zavolaj na známy telefónny kontakt.`,
    },
    {
      kind: "example",
      heading: `Vzor #4 — „Faktúra na zaplatenie" s prílohou .zip`,
      visual: {
        kind: "email",
        from: "Účtovníctvo",
        fromEmail: "uctovnictvo@mojadodavka-faktura.com",
        subject: "Faktúra č. 2024-1187 na úhradu",
        body: `V prílohe nájdete faktúru č. 2024-1187 splatnú do 7 dní. Pri pochybnostiach kontaktujte naše účtovníctvo. Príloha: faktura_1187.zip`,
      },
      commentary: `Faktúra v .zip alebo .iso prílohe je takmer vždy malware (škodlivý softvér). Skutočné faktúry sú PDF priamo alebo cez známy systém. Ak nečakáš faktúru od tejto firmy — neotváraj.`,
    },
    {
      kind: "example",
      heading: `Vzor #5 — „LinkedIn" — nová pracovná ponuka`,
      visual: {
        kind: "email",
        from: "LinkedIn Talent",
        fromEmail: "talent@linkedin-careers-eu.com",
        subject: "Senior Engineer @ Apple — máme záujem o váš profil",
        body: `Ahoj, váš profil zaujal recruitera spoločnosti Apple. Pozícia: Senior Software Engineer, plat 150-200k EUR. Nižšie nájdete odkaz na pohovor — vyplňte krátky profil cez náš portál.`,
        cta: "Otvoriť profil",
      },
      commentary: `LinkedIn píše z @linkedin.com. Doména linkedin-careers-eu.com nepatrí im. Príliš dobrá ponuka („Apple, 200k") je páka — útočník chce, aby si vyplnil falošný „profil" s heslami.`,
    },
    {
      kind: "example",
      heading: `Vzor #6 — „PayPal: nová prihláška z neznámeho zariadenia"`,
      visual: {
        kind: "email",
        from: "PayPal Service",
        fromEmail: "service@paypal-account-protect.com",
        subject: "Bola zaznamenaná nová prihláška z neznámeho zariadenia",
        body: `Z vášho účtu PayPal sa práve niekto pokúsil prihlásiť z neznámeho zariadenia (Praha, Česko). Ak ste to neboli vy, okamžite zabezpečte účet.`,
        cta: "Zabezpečiť účet",
      },
      commentary: `PayPal píše z @paypal.com. Aj samotná správa môže byť pravdivá pocitovo (mohol by si sa skutočne prihlasovať z iného miesta), ale doména a CTA tlačia na rýchle kliknutie.`,
    },
    {
      kind: "redflags",
      heading: "10 vecí, na ktoré sa pozri pred kliknutím",
      flags: [
        `Doména odosielateľa nepatrí firme — pozri si ju ZA znakom @, nie len zobrazené meno.`,
        `Generické oslovenie („Vážený klient", „Dear Customer") namiesto mena.`,
        `Tlak na čas („do 24 hodín", „okamžite", „inak").`,
        `Hroziaca strata (zablokovanie účtu, vymazanie dát, zákonné konanie).`,
        `Príliš dobrá ponuka (výhra, recruiter z Apple, vrátenie peňazí).`,
        `Príloha .zip / .iso / .exe / .scr — nikdy neotvárať.`,
        `Pravopisné chyby alebo zlý preklad (najmä pri „banke SR").`,
        `Žiadosť o heslo, OTP (jednorazový overovací kód) či PIN cez e-mail.`,
        `Odkaz, ktorý po nabehnutí kurzorom ukazuje inú doménu ako text odkazu.`,
        `Nečakaná faktúra od dodávateľa, s ktorým nemáš zmluvu.`,
      ],
    },
    {
      kind: "checklist",
      heading: "Rýchla 30-sekundová kontrola",
      items: [
        { good: false, text: `Doména za @ vyzerá ako „banka-secure.online".` },
        { good: false, text: "Som pozvaný na pohovor, hoci som nikam neposielal CV." },
        { good: false, text: "E-mail mi tlačí čas alebo ma straší." },
        { good: true, text: "Doména súhlasí — slsp.sk, microsoft.com, paypal.com." },
        { good: true, text: "E-mail rieši niečo, čo som naozaj v posledných dňoch robil." },
        { good: true, text: "Otvorím stránku ručne, nie z odkazu v e-maile." },
      ],
    },
    {
      kind: "do_dont",
      heading: "Pravidlá",
      do: [
        `Pri každom „bankovom" e-maile otvor banku ručne v prehliadači.`,
        `Zapni 2FA (dvojfaktorové overenie) na e-mail (Gmail, Outlook). Ten je kľúčom k všetkému ostatnému.`,
        `Pri urgentnom príkaze od „šéfa" mu zavolaj — neodpisuj e-mailom.`,
        `Prílohu otváraj iba vtedy, keď ju očakávaš a poznáš odosielateľa.`,
      ],
      dont: [
        `Nedôveruj zobrazenému menu odosielateľa — len doméne za @.`,
        `Neklikaj na odkazy „obnoviť heslo" z e-mailu — vždy ručne.`,
        `Nepreposielaj podozrivý e-mail kolegom — môžu kliknúť za teba.`,
        `Nedávaj odpoveď „STOP" ani „odhlásiť" útočníkovi.`,
      ],
    },
    {
      kind: "scenario",
      heading: "Reálny scenár — pondelok ráno",
      story: `Otvoríš Outlook. „Microsoft: vaše heslo vyprší dnes o 18:00, kliknite a obnovte." Si v strese, máš online meeting o 5 minút. Klikneš?`,
      right_action: `Nie. Otvoríš si konto Microsoft ručne v inej karte (account.microsoft.com) a prihlásiš sa zaužívaným postupom. Tam buď naozaj uvidíš upozornenie, alebo nie. Žiadnu „obnovu" cez e-mail nikdy nerob.`,
    },
  ],
  sources: [
    { label: "NCKB — phishing detail", url: "https://www.sk-cert.sk/" },
    { label: "Microsoft — Identifying phishing", url: "https://support.microsoft.com/" },
    { label: "PayPal — bezpečnostné centrum", url: "https://www.paypal.com/sk/security" },
  ],
};
