// E47.1 / E48.1 — manifest of every valid /docs/* slug. Generated by
// inspecting every `docs.links[].href` in the explainer i18n bundles
// (src/i18n/locales/sk/admin.json `explainers.*.docs.links` and
// src/i18n/locales/sk/app-explainers.json same). When a new explainer
// link is added, add its slug here too — the static test at
// tests/i18n/docs-manifest.test.ts fails closed otherwise.
//
// Currently every slug renders the shared "coming soon" stub. As real
// documentation lands per slug, replace the value with a richer
// descriptor (title override, body MDX, etc.) — the route handlers
// already differentiate based on the entry shape.

export interface DocStub {
  /** When true, the page renders the shared "coming soon" stub. */
  stub: true;
}

export type DocEntry = DocStub;

const STUB: DocStub = { stub: true };

export const ADMIN_DOCS: Record<string, DocEntry> = {
  aal2: STUB,
  "ai-generator": STUB,
  "answer-sets": STUB,
  "answer-sets-versioning": STUB,
  audit: STUB,
  blog: STUB,
  branding: STUB,
  categories: STUB,
  "categories-slugs": STUB,
  dashboard: STUB,
  "dpa-anonymisation": STUB,
  "dpa-requests": STUB,
  dsr: STUB,
  "dsr-runbook": STUB,
  footer: STUB,
  header: STUB,
  legal: STUB,
  navigation: STUB,
  pages: STUB,
  "pages-slugs": STUB,
  publishing: STUB,
  questions: STUB,
  "quick-test": STUB,
  reports: STUB,
  "reports-escalation": STUB,
  retention: STUB,
  security: STUB,
  "security-backup-codes": STUB,
  settings: STUB,
  "share-card": STUB,
  "share-card-cache": STUB,
  subprocessors: STUB,
  support: STUB,
  "support-escalation": STUB,
  tests: STUB,
  trainings: STUB,
  users: STUB,
};

export const APP_DOCS: Record<string, DocEntry> = {
  audiences: STUB,
  "audiences-tags": STUB,
  dashboard: STUB,
  digest: STUB,
  "edu-tests": STUB,
  "edu-tests-claim": STUB,
  help: STUB,
  "help-support": STUB,
  history: STUB,
  "history-events": STUB,
  library: STUB,
  "library-insert": STUB,
  notifications: STUB,
  "notifications-email": STUB,
  profile: STUB,
  "profile-gdpr": STUB,
  "profile-security": STUB,
  teams: STUB,
  "teams-rls": STUB,
  templates: STUB,
  "templates-gdpr": STUB,
  "tests-create": STUB,
  "tests-sharing": STUB,
};

export function lookupDoc(area: "admin" | "app", slug: string): DocEntry | null {
  const map = area === "admin" ? ADMIN_DOCS : APP_DOCS;
  return map[slug] ?? null;
}
