export const ROUTES = {
  home: "/",
  test: "/test",
  testy: "/tests",
  testySlug: "/tests/$slug",
  zostav: "/test/zostav",
  zostava: "/test/zostava/$id",
  zostavaVysledky: "/test/zostava/$id/vysledky",
  skoly: "/schools",
  skolenia: "/courses",
  skoleniaSlug: "/courses/$slug",
  podpora: "/support",
  sponzori: "/sponsors",
  sponzoriVsetci: "/sponsors/all",
  spravovat: "/manage-support",
  privacy: "/privacy",
  cookies: "/cookies",
  oProjecte: "/about",
  zmeny: "/changelog",
  kontakt: "/contact",
  blog: "/blog",
} as const;
