#!/usr/bin/env tsx
// E55.4 — generate the idempotent SQL backfill that imports the static
// courses into public.blog_posts as content_type='lesson' rows (the
// DB-unified academy). Deterministic: re-running with unchanged course
// modules produces a byte-identical file. The SQL itself is idempotent
// (ON CONFLICT (slug) DO UPDATE), so the user can re-apply it safely.
//
//   npx tsx scripts/generate-academy-import.ts
//
// Output: supabase/backfills/20260628_academy_import_lessons.sql
// Per CLAUDE.md, DB changes ship as code; the user runs this SQL against
// prod Supabase manually after the PR merges.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { COURSES } from "@/content/courses";
import { courseToAcademyRow, type AcademyLessonRow } from "@/lib/academy/course-to-row";

const OUT = join(
  dirname(dirname(fileURLToPath(import.meta.url))),
  "supabase/backfills/20260628_academy_import_lessons.sql",
);

// Dollar-quote with a tag guaranteed absent from the payload.
function dollar(value: string, tag: string): string {
  let t = tag;
  while (value.includes(`$${t}$`)) t += "_";
  return `$${t}$${value}$${t}$`;
}

function insert(row: AcademyLessonRow): string {
  return `INSERT INTO public.blog_posts
  (slug, language, category_id, author_id, title, subtitle, excerpt, body_mdx,
   content_type, difficulty, estimated_minutes, hero_emoji, reading_minutes,
   sources_jsonb, status, published_at)
VALUES (
  ${dollar(row.slug, "slug")}, 'sk',
  (SELECT id FROM public.blog_categories WHERE slug = ${dollar(row.category_slug, "cat")}),
  (SELECT id FROM public.blog_authors WHERE slug = ${dollar(row.author_slug, "auth")}),
  ${dollar(row.title, "title")},
  ${dollar(row.subtitle, "sub")},
  ${dollar(row.excerpt, "exc")},
  ${dollar(row.body_mdx, "body")},
  'lesson', ${dollar(row.difficulty, "diff")}, ${row.estimated_minutes}, ${dollar(row.hero_emoji, "emoji")}, ${row.reading_minutes},
  ${dollar(JSON.stringify(row.sources), "src")}::jsonb,
  'published', ${dollar(row.published_at, "pub")}
)
ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  author_id = EXCLUDED.author_id,
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  excerpt = EXCLUDED.excerpt,
  body_mdx = EXCLUDED.body_mdx,
  content_type = EXCLUDED.content_type,
  difficulty = EXCLUDED.difficulty,
  estimated_minutes = EXCLUDED.estimated_minutes,
  hero_emoji = EXCLUDED.hero_emoji,
  reading_minutes = EXCLUDED.reading_minutes,
  sources_jsonb = EXCLUDED.sources_jsonb,
  status = EXCLUDED.status,
  published_at = EXCLUDED.published_at,
  updated_at = now();`;
}

const rows = COURSES.map(courseToAcademyRow);

const header = `-- ============================================================================
-- E55.4 — Academy lesson import (${rows.length} courses → blog_posts lessons)
-- GENERATED by scripts/generate-academy-import.ts — do not edit by hand.
-- Source: tasks/PLAN-2026-06-28-E55-academy-merge.md
-- ============================================================================
-- Idempotent: ON CONFLICT (slug) DO UPDATE. Safe to re-run. Requires the
-- E55.1 academy columns migration (20260628100000_academy_columns.sql) and
-- the blog schema (categories + the 'subenai-editorial' author) to be applied
-- first. Run this against prod Supabase AFTER the E55 PR merges.
-- ============================================================================

BEGIN;
`;

const body = rows.map(insert).join("\n\n");
writeFileSync(OUT, `${header}\n${body}\n\nCOMMIT;\n`);
console.log(`Wrote ${rows.length} lessons → ${OUT}`);
