/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZmenyRouteImport } from './routes/zmeny'
import { Route as SpravovatPodporuRouteImport } from './routes/spravovat-podporu'
import { Route as SponzoriRouteImport } from './routes/sponzori'
import { Route as SkolyRouteImport } from './routes/skoly'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PodporaRouteImport } from './routes/podpora'
import { Route as OProjekteRouteImport } from './routes/o-projekte'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestyIndexRouteImport } from './routes/testy.index'
import { Route as TestIndexRouteImport } from './routes/test.index'
import { Route as SponzoriIndexRouteImport } from './routes/sponzori.index'
import { Route as SkoleniaIndexRouteImport } from './routes/skolenia.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TestySlugRouteImport } from './routes/testy.$slug'
import { Route as TestZostavRouteImport } from './routes/test.zostav'
import { Route as TShareIdRouteImport } from './routes/t.$shareId'
import { Route as SponzoriVsetciRouteImport } from './routes/sponzori.vsetci'
import { Route as SkoleniaSlugRouteImport } from './routes/skolenia.$slug'
import { Route as RShareIdRouteImport } from './routes/r.$shareId'
import { Route as PodakovanieSessionIdRouteImport } from './routes/podakovanie.$sessionId'
import { Route as AppTeamsRouteImport } from './routes/app.teams'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppLibraryRouteImport } from './routes/app.library'
import { Route as AppHelpRouteImport } from './routes/app.help'
import { Route as AppAudiencesRouteImport } from './routes/app.audiences'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTrainingsRouteImport } from './routes/admin/trainings'
import { Route as AdminSupportRouteImport } from './routes/admin/support'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminRespondentsRouteImport } from './routes/admin/respondents'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminQuestionsRouteImport } from './routes/admin/questions'
import { Route as AdminDsrRouteImport } from './routes/admin/dsr'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminAnswerSetsRouteImport } from './routes/admin/answer-sets'
import { Route as AppTestsIndexRouteImport } from './routes/app.tests.index'
import { Route as TestZostavaIdRouteImport } from './routes/test.zostava.$id'
import { Route as AppTestsNewRouteImport } from './routes/app.tests.new'
import { Route as AppTestsTestIdRouteImport } from './routes/app.tests.$testId'
import { Route as AppSetsSetIdRouteImport } from './routes/app.sets.$setId'
import { Route as AppLegalDsrRouteImport } from './routes/app.legal.dsr'
import { Route as AppAccountSecurityRouteImport } from './routes/app.account.security'
import { Route as AppAccountProfileRouteImport } from './routes/app.account.profile'
import { Route as AdminAnswerSetsSetIdRouteImport } from './routes/admin/answer-sets.$setId'
import { Route as TestZostavaIdVysledkyRouteImport } from './routes/test.zostava.$id.vysledky'

const ZmenyRoute = ZmenyRouteImport.update({
  id: '/zmeny',
  path: '/zmeny',
  getParentRoute: () => rootRouteImport,
} as any)
const SpravovatPodporuRoute = SpravovatPodporuRouteImport.update({
  id: '/spravovat-podporu',
  path: '/spravovat-podporu',
  getParentRoute: () => rootRouteImport,
} as any)
const SponzoriRoute = SponzoriRouteImport.update({
  id: '/sponzori',
  path: '/sponzori',
  getParentRoute: () => rootRouteImport,
} as any)
const SkolyRoute = SkolyRouteImport.update({
  id: '/skoly',
  path: '/skoly',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PodporaRoute = PodporaRouteImport.update({
  id: '/podpora',
  path: '/podpora',
  getParentRoute: () => rootRouteImport,
} as any)
const OProjekteRoute = OProjekteRouteImport.update({
  id: '/o-projekte',
  path: '/o-projekte',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestyIndexRoute = TestyIndexRouteImport.update({
  id: '/testy/',
  path: '/testy/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const SponzoriIndexRoute = SponzoriIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SponzoriRoute,
} as any)
const SkoleniaIndexRoute = SkoleniaIndexRouteImport.update({
  id: '/skolenia/',
  path: '/skolenia/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TestySlugRoute = TestySlugRouteImport.update({
  id: '/testy/$slug',
  path: '/testy/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TestZostavRoute = TestZostavRouteImport.update({
  id: '/test/zostav',
  path: '/test/zostav',
  getParentRoute: () => rootRouteImport,
} as any)
const TShareIdRoute = TShareIdRouteImport.update({
  id: '/t/$shareId',
  path: '/t/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const SponzoriVsetciRoute = SponzoriVsetciRouteImport.update({
  id: '/vsetci',
  path: '/vsetci',
  getParentRoute: () => SponzoriRoute,
} as any)
const SkoleniaSlugRoute = SkoleniaSlugRouteImport.update({
  id: '/skolenia/$slug',
  path: '/skolenia/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RShareIdRoute = RShareIdRouteImport.update({
  id: '/r/$shareId',
  path: '/r/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const PodakovanieSessionIdRoute = PodakovanieSessionIdRouteImport.update({
  id: '/podakovanie/$sessionId',
  path: '/podakovanie/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamsRoute = AppTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppAudiencesRoute = AppAudiencesRouteImport.update({
  id: '/audiences',
  path: '/audiences',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrainingsRoute = AdminTrainingsRouteImport.update({
  id: '/trainings',
  path: '/trainings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRespondentsRoute = AdminRespondentsRouteImport.update({
  id: '/respondents',
  path: '/respondents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDsrRoute = AdminDsrRouteImport.update({
  id: '/dsr',
  path: '/dsr',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnswerSetsRoute = AdminAnswerSetsRouteImport.update({
  id: '/answer-sets',
  path: '/answer-sets',
  getParentRoute: () => AdminRoute,
} as any)
const AppTestsIndexRoute = AppTestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => AppRoute,
} as any)
const TestZostavaIdRoute = TestZostavaIdRouteImport.update({
  id: '/test/zostava/$id',
  path: '/test/zostava/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTestsNewRoute = AppTestsNewRouteImport.update({
  id: '/tests/new',
  path: '/tests/new',
  getParentRoute: () => AppRoute,
} as any)
const AppTestsTestIdRoute = AppTestsTestIdRouteImport.update({
  id: '/tests/$testId',
  path: '/tests/$testId',
  getParentRoute: () => AppRoute,
} as any)
const AppSetsSetIdRoute = AppSetsSetIdRouteImport.update({
  id: '/sets/$setId',
  path: '/sets/$setId',
  getParentRoute: () => AppRoute,
} as any)
const AppLegalDsrRoute = AppLegalDsrRouteImport.update({
  id: '/legal/dsr',
  path: '/legal/dsr',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountSecurityRoute = AppAccountSecurityRouteImport.update({
  id: '/account/security',
  path: '/account/security',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountProfileRoute = AppAccountProfileRouteImport.update({
  id: '/account/profile',
  path: '/account/profile',
  getParentRoute: () => AppRoute,
} as any)
const AdminAnswerSetsSetIdRoute = AdminAnswerSetsSetIdRouteImport.update({
  id: '/$setId',
  path: '/$setId',
  getParentRoute: () => AdminAnswerSetsRoute,
} as any)
const TestZostavaIdVysledkyRoute = TestZostavaIdVysledkyRouteImport.update({
  id: '/vysledky',
  path: '/vysledky',
  getParentRoute: () => TestZostavaIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/kontakt': typeof KontaktRoute
  '/login': typeof LoginRoute
  '/o-projekte': typeof OProjekteRoute
  '/podpora': typeof PodporaRoute
  '/privacy': typeof PrivacyRoute
  '/skoly': typeof SkolyRoute
  '/sponzori': typeof SponzoriRouteWithChildren
  '/spravovat-podporu': typeof SpravovatPodporuRoute
  '/zmeny': typeof ZmenyRoute
  '/admin/answer-sets': typeof AdminAnswerSetsRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dsr': typeof AdminDsrRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/respondents': typeof AdminRespondentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/trainings': typeof AdminTrainingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/audiences': typeof AppAudiencesRoute
  '/app/help': typeof AppHelpRoute
  '/app/library': typeof AppLibraryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/teams': typeof AppTeamsRoute
  '/podakovanie/$sessionId': typeof PodakovanieSessionIdRoute
  '/r/$shareId': typeof RShareIdRoute
  '/skolenia/$slug': typeof SkoleniaSlugRoute
  '/sponzori/vsetci': typeof SponzoriVsetciRoute
  '/t/$shareId': typeof TShareIdRoute
  '/test/zostav': typeof TestZostavRoute
  '/testy/$slug': typeof TestySlugRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/skolenia/': typeof SkoleniaIndexRoute
  '/sponzori/': typeof SponzoriIndexRoute
  '/test/': typeof TestIndexRoute
  '/testy/': typeof TestyIndexRoute
  '/admin/answer-sets/$setId': typeof AdminAnswerSetsSetIdRoute
  '/app/account/profile': typeof AppAccountProfileRoute
  '/app/account/security': typeof AppAccountSecurityRoute
  '/app/legal/dsr': typeof AppLegalDsrRoute
  '/app/sets/$setId': typeof AppSetsSetIdRoute
  '/app/tests/$testId': typeof AppTestsTestIdRoute
  '/app/tests/new': typeof AppTestsNewRoute
  '/test/zostava/$id': typeof TestZostavaIdRouteWithChildren
  '/app/tests/': typeof AppTestsIndexRoute
  '/test/zostava/$id/vysledky': typeof TestZostavaIdVysledkyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/kontakt': typeof KontaktRoute
  '/login': typeof LoginRoute
  '/o-projekte': typeof OProjekteRoute
  '/podpora': typeof PodporaRoute
  '/privacy': typeof PrivacyRoute
  '/skoly': typeof SkolyRoute
  '/spravovat-podporu': typeof SpravovatPodporuRoute
  '/zmeny': typeof ZmenyRoute
  '/admin/answer-sets': typeof AdminAnswerSetsRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dsr': typeof AdminDsrRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/respondents': typeof AdminRespondentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/trainings': typeof AdminTrainingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/audiences': typeof AppAudiencesRoute
  '/app/help': typeof AppHelpRoute
  '/app/library': typeof AppLibraryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/teams': typeof AppTeamsRoute
  '/podakovanie/$sessionId': typeof PodakovanieSessionIdRoute
  '/r/$shareId': typeof RShareIdRoute
  '/skolenia/$slug': typeof SkoleniaSlugRoute
  '/sponzori/vsetci': typeof SponzoriVsetciRoute
  '/t/$shareId': typeof TShareIdRoute
  '/test/zostav': typeof TestZostavRoute
  '/testy/$slug': typeof TestySlugRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/skolenia': typeof SkoleniaIndexRoute
  '/sponzori': typeof SponzoriIndexRoute
  '/test': typeof TestIndexRoute
  '/testy': typeof TestyIndexRoute
  '/admin/answer-sets/$setId': typeof AdminAnswerSetsSetIdRoute
  '/app/account/profile': typeof AppAccountProfileRoute
  '/app/account/security': typeof AppAccountSecurityRoute
  '/app/legal/dsr': typeof AppLegalDsrRoute
  '/app/sets/$setId': typeof AppSetsSetIdRoute
  '/app/tests/$testId': typeof AppTestsTestIdRoute
  '/app/tests/new': typeof AppTestsNewRoute
  '/test/zostava/$id': typeof TestZostavaIdRouteWithChildren
  '/app/tests': typeof AppTestsIndexRoute
  '/test/zostava/$id/vysledky': typeof TestZostavaIdVysledkyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/kontakt': typeof KontaktRoute
  '/login': typeof LoginRoute
  '/o-projekte': typeof OProjekteRoute
  '/podpora': typeof PodporaRoute
  '/privacy': typeof PrivacyRoute
  '/skoly': typeof SkolyRoute
  '/sponzori': typeof SponzoriRouteWithChildren
  '/spravovat-podporu': typeof SpravovatPodporuRoute
  '/zmeny': typeof ZmenyRoute
  '/admin/answer-sets': typeof AdminAnswerSetsRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dsr': typeof AdminDsrRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/respondents': typeof AdminRespondentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/trainings': typeof AdminTrainingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/audiences': typeof AppAudiencesRoute
  '/app/help': typeof AppHelpRoute
  '/app/library': typeof AppLibraryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/teams': typeof AppTeamsRoute
  '/podakovanie/$sessionId': typeof PodakovanieSessionIdRoute
  '/r/$shareId': typeof RShareIdRoute
  '/skolenia/$slug': typeof SkoleniaSlugRoute
  '/sponzori/vsetci': typeof SponzoriVsetciRoute
  '/t/$shareId': typeof TShareIdRoute
  '/test/zostav': typeof TestZostavRoute
  '/testy/$slug': typeof TestySlugRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/skolenia/': typeof SkoleniaIndexRoute
  '/sponzori/': typeof SponzoriIndexRoute
  '/test/': typeof TestIndexRoute
  '/testy/': typeof TestyIndexRoute
  '/admin/answer-sets/$setId': typeof AdminAnswerSetsSetIdRoute
  '/app/account/profile': typeof AppAccountProfileRoute
  '/app/account/security': typeof AppAccountSecurityRoute
  '/app/legal/dsr': typeof AppLegalDsrRoute
  '/app/sets/$setId': typeof AppSetsSetIdRoute
  '/app/tests/$testId': typeof AppTestsTestIdRoute
  '/app/tests/new': typeof AppTestsNewRoute
  '/test/zostava/$id': typeof TestZostavaIdRouteWithChildren
  '/app/tests/': typeof AppTestsIndexRoute
  '/test/zostava/$id/vysledky': typeof TestZostavaIdVysledkyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/cookies'
    | '/kontakt'
    | '/login'
    | '/o-projekte'
    | '/podpora'
    | '/privacy'
    | '/skoly'
    | '/sponzori'
    | '/spravovat-podporu'
    | '/zmeny'
    | '/admin/answer-sets'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/dsr'
    | '/admin/questions'
    | '/admin/reports'
    | '/admin/respondents'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/trainings'
    | '/admin/users'
    | '/app/audiences'
    | '/app/help'
    | '/app/library'
    | '/app/notifications'
    | '/app/teams'
    | '/podakovanie/$sessionId'
    | '/r/$shareId'
    | '/skolenia/$slug'
    | '/sponzori/vsetci'
    | '/t/$shareId'
    | '/test/zostav'
    | '/testy/$slug'
    | '/admin/'
    | '/app/'
    | '/skolenia/'
    | '/sponzori/'
    | '/test/'
    | '/testy/'
    | '/admin/answer-sets/$setId'
    | '/app/account/profile'
    | '/app/account/security'
    | '/app/legal/dsr'
    | '/app/sets/$setId'
    | '/app/tests/$testId'
    | '/app/tests/new'
    | '/test/zostava/$id'
    | '/app/tests/'
    | '/test/zostava/$id/vysledky'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookies'
    | '/kontakt'
    | '/login'
    | '/o-projekte'
    | '/podpora'
    | '/privacy'
    | '/skoly'
    | '/spravovat-podporu'
    | '/zmeny'
    | '/admin/answer-sets'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/dsr'
    | '/admin/questions'
    | '/admin/reports'
    | '/admin/respondents'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/trainings'
    | '/admin/users'
    | '/app/audiences'
    | '/app/help'
    | '/app/library'
    | '/app/notifications'
    | '/app/teams'
    | '/podakovanie/$sessionId'
    | '/r/$shareId'
    | '/skolenia/$slug'
    | '/sponzori/vsetci'
    | '/t/$shareId'
    | '/test/zostav'
    | '/testy/$slug'
    | '/admin'
    | '/app'
    | '/skolenia'
    | '/sponzori'
    | '/test'
    | '/testy'
    | '/admin/answer-sets/$setId'
    | '/app/account/profile'
    | '/app/account/security'
    | '/app/legal/dsr'
    | '/app/sets/$setId'
    | '/app/tests/$testId'
    | '/app/tests/new'
    | '/test/zostava/$id'
    | '/app/tests'
    | '/test/zostava/$id/vysledky'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/cookies'
    | '/kontakt'
    | '/login'
    | '/o-projekte'
    | '/podpora'
    | '/privacy'
    | '/skoly'
    | '/sponzori'
    | '/spravovat-podporu'
    | '/zmeny'
    | '/admin/answer-sets'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/dsr'
    | '/admin/questions'
    | '/admin/reports'
    | '/admin/respondents'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/trainings'
    | '/admin/users'
    | '/app/audiences'
    | '/app/help'
    | '/app/library'
    | '/app/notifications'
    | '/app/teams'
    | '/podakovanie/$sessionId'
    | '/r/$shareId'
    | '/skolenia/$slug'
    | '/sponzori/vsetci'
    | '/t/$shareId'
    | '/test/zostav'
    | '/testy/$slug'
    | '/admin/'
    | '/app/'
    | '/skolenia/'
    | '/sponzori/'
    | '/test/'
    | '/testy/'
    | '/admin/answer-sets/$setId'
    | '/app/account/profile'
    | '/app/account/security'
    | '/app/legal/dsr'
    | '/app/sets/$setId'
    | '/app/tests/$testId'
    | '/app/tests/new'
    | '/test/zostava/$id'
    | '/app/tests/'
    | '/test/zostava/$id/vysledky'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  CookiesRoute: typeof CookiesRoute
  KontaktRoute: typeof KontaktRoute
  LoginRoute: typeof LoginRoute
  OProjekteRoute: typeof OProjekteRoute
  PodporaRoute: typeof PodporaRoute
  PrivacyRoute: typeof PrivacyRoute
  SkolyRoute: typeof SkolyRoute
  SponzoriRoute: typeof SponzoriRouteWithChildren
  SpravovatPodporuRoute: typeof SpravovatPodporuRoute
  ZmenyRoute: typeof ZmenyRoute
  PodakovanieSessionIdRoute: typeof PodakovanieSessionIdRoute
  RShareIdRoute: typeof RShareIdRoute
  SkoleniaSlugRoute: typeof SkoleniaSlugRoute
  TShareIdRoute: typeof TShareIdRoute
  TestZostavRoute: typeof TestZostavRoute
  TestySlugRoute: typeof TestySlugRoute
  SkoleniaIndexRoute: typeof SkoleniaIndexRoute
  TestIndexRoute: typeof TestIndexRoute
  TestyIndexRoute: typeof TestyIndexRoute
  TestZostavaIdRoute: typeof TestZostavaIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zmeny': {
      id: '/zmeny'
      path: '/zmeny'
      fullPath: '/zmeny'
      preLoaderRoute: typeof ZmenyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spravovat-podporu': {
      id: '/spravovat-podporu'
      path: '/spravovat-podporu'
      fullPath: '/spravovat-podporu'
      preLoaderRoute: typeof SpravovatPodporuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponzori': {
      id: '/sponzori'
      path: '/sponzori'
      fullPath: '/sponzori'
      preLoaderRoute: typeof SponzoriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skoly': {
      id: '/skoly'
      path: '/skoly'
      fullPath: '/skoly'
      preLoaderRoute: typeof SkolyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podpora': {
      id: '/podpora'
      path: '/podpora'
      fullPath: '/podpora'
      preLoaderRoute: typeof PodporaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-projekte': {
      id: '/o-projekte'
      path: '/o-projekte'
      fullPath: '/o-projekte'
      preLoaderRoute: typeof OProjekteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testy/': {
      id: '/testy/'
      path: '/testy'
      fullPath: '/testy/'
      preLoaderRoute: typeof TestyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponzori/': {
      id: '/sponzori/'
      path: '/'
      fullPath: '/sponzori/'
      preLoaderRoute: typeof SponzoriIndexRouteImport
      parentRoute: typeof SponzoriRoute
    }
    '/skolenia/': {
      id: '/skolenia/'
      path: '/skolenia'
      fullPath: '/skolenia/'
      preLoaderRoute: typeof SkoleniaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/testy/$slug': {
      id: '/testy/$slug'
      path: '/testy/$slug'
      fullPath: '/testy/$slug'
      preLoaderRoute: typeof TestySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/zostav': {
      id: '/test/zostav'
      path: '/test/zostav'
      fullPath: '/test/zostav'
      preLoaderRoute: typeof TestZostavRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$shareId': {
      id: '/t/$shareId'
      path: '/t/$shareId'
      fullPath: '/t/$shareId'
      preLoaderRoute: typeof TShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponzori/vsetci': {
      id: '/sponzori/vsetci'
      path: '/vsetci'
      fullPath: '/sponzori/vsetci'
      preLoaderRoute: typeof SponzoriVsetciRouteImport
      parentRoute: typeof SponzoriRoute
    }
    '/skolenia/$slug': {
      id: '/skolenia/$slug'
      path: '/skolenia/$slug'
      fullPath: '/skolenia/$slug'
      preLoaderRoute: typeof SkoleniaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$shareId': {
      id: '/r/$shareId'
      path: '/r/$shareId'
      fullPath: '/r/$shareId'
      preLoaderRoute: typeof RShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podakovanie/$sessionId': {
      id: '/podakovanie/$sessionId'
      path: '/podakovanie/$sessionId'
      fullPath: '/podakovanie/$sessionId'
      preLoaderRoute: typeof PodakovanieSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/teams': {
      id: '/app/teams'
      path: '/teams'
      fullPath: '/app/teams'
      preLoaderRoute: typeof AppTeamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library': {
      id: '/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/help': {
      id: '/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audiences': {
      id: '/app/audiences'
      path: '/audiences'
      fullPath: '/app/audiences'
      preLoaderRoute: typeof AppAudiencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/trainings': {
      id: '/admin/trainings'
      path: '/trainings'
      fullPath: '/admin/trainings'
      preLoaderRoute: typeof AdminTrainingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/respondents': {
      id: '/admin/respondents'
      path: '/respondents'
      fullPath: '/admin/respondents'
      preLoaderRoute: typeof AdminRespondentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dsr': {
      id: '/admin/dsr'
      path: '/dsr'
      fullPath: '/admin/dsr'
      preLoaderRoute: typeof AdminDsrRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/answer-sets': {
      id: '/admin/answer-sets'
      path: '/answer-sets'
      fullPath: '/admin/answer-sets'
      preLoaderRoute: typeof AdminAnswerSetsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/tests/': {
      id: '/app/tests/'
      path: '/tests'
      fullPath: '/app/tests/'
      preLoaderRoute: typeof AppTestsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/test/zostava/$id': {
      id: '/test/zostava/$id'
      path: '/test/zostava/$id'
      fullPath: '/test/zostava/$id'
      preLoaderRoute: typeof TestZostavaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tests/new': {
      id: '/app/tests/new'
      path: '/tests/new'
      fullPath: '/app/tests/new'
      preLoaderRoute: typeof AppTestsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tests/$testId': {
      id: '/app/tests/$testId'
      path: '/tests/$testId'
      fullPath: '/app/tests/$testId'
      preLoaderRoute: typeof AppTestsTestIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sets/$setId': {
      id: '/app/sets/$setId'
      path: '/sets/$setId'
      fullPath: '/app/sets/$setId'
      preLoaderRoute: typeof AppSetsSetIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/legal/dsr': {
      id: '/app/legal/dsr'
      path: '/legal/dsr'
      fullPath: '/app/legal/dsr'
      preLoaderRoute: typeof AppLegalDsrRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/account/security': {
      id: '/app/account/security'
      path: '/account/security'
      fullPath: '/app/account/security'
      preLoaderRoute: typeof AppAccountSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/account/profile': {
      id: '/app/account/profile'
      path: '/account/profile'
      fullPath: '/app/account/profile'
      preLoaderRoute: typeof AppAccountProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/answer-sets/$setId': {
      id: '/admin/answer-sets/$setId'
      path: '/$setId'
      fullPath: '/admin/answer-sets/$setId'
      preLoaderRoute: typeof AdminAnswerSetsSetIdRouteImport
      parentRoute: typeof AdminAnswerSetsRoute
    }
    '/test/zostava/$id/vysledky': {
      id: '/test/zostava/$id/vysledky'
      path: '/vysledky'
      fullPath: '/test/zostava/$id/vysledky'
      preLoaderRoute: typeof TestZostavaIdVysledkyRouteImport
      parentRoute: typeof TestZostavaIdRoute
    }
  }
}

interface AdminAnswerSetsRouteChildren {
  AdminAnswerSetsSetIdRoute: typeof AdminAnswerSetsSetIdRoute
}

const AdminAnswerSetsRouteChildren: AdminAnswerSetsRouteChildren = {
  AdminAnswerSetsSetIdRoute: AdminAnswerSetsSetIdRoute,
}

const AdminAnswerSetsRouteWithChildren = AdminAnswerSetsRoute._addFileChildren(
  AdminAnswerSetsRouteChildren,
)

interface AdminRouteChildren {
  AdminAnswerSetsRoute: typeof AdminAnswerSetsRouteWithChildren
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDsrRoute: typeof AdminDsrRoute
  AdminQuestionsRoute: typeof AdminQuestionsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRespondentsRoute: typeof AdminRespondentsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTrainingsRoute: typeof AdminTrainingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnswerSetsRoute: AdminAnswerSetsRouteWithChildren,
  AdminAuditRoute: AdminAuditRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminDsrRoute: AdminDsrRoute,
  AdminQuestionsRoute: AdminQuestionsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRespondentsRoute: AdminRespondentsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTrainingsRoute: AdminTrainingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAudiencesRoute: typeof AppAudiencesRoute
  AppHelpRoute: typeof AppHelpRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppTeamsRoute: typeof AppTeamsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAccountProfileRoute: typeof AppAccountProfileRoute
  AppAccountSecurityRoute: typeof AppAccountSecurityRoute
  AppLegalDsrRoute: typeof AppLegalDsrRoute
  AppSetsSetIdRoute: typeof AppSetsSetIdRoute
  AppTestsTestIdRoute: typeof AppTestsTestIdRoute
  AppTestsNewRoute: typeof AppTestsNewRoute
  AppTestsIndexRoute: typeof AppTestsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAudiencesRoute: AppAudiencesRoute,
  AppHelpRoute: AppHelpRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppTeamsRoute: AppTeamsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAccountProfileRoute: AppAccountProfileRoute,
  AppAccountSecurityRoute: AppAccountSecurityRoute,
  AppLegalDsrRoute: AppLegalDsrRoute,
  AppSetsSetIdRoute: AppSetsSetIdRoute,
  AppTestsTestIdRoute: AppTestsTestIdRoute,
  AppTestsNewRoute: AppTestsNewRoute,
  AppTestsIndexRoute: AppTestsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SponzoriRouteChildren {
  SponzoriVsetciRoute: typeof SponzoriVsetciRoute
  SponzoriIndexRoute: typeof SponzoriIndexRoute
}

const SponzoriRouteChildren: SponzoriRouteChildren = {
  SponzoriVsetciRoute: SponzoriVsetciRoute,
  SponzoriIndexRoute: SponzoriIndexRoute,
}

const SponzoriRouteWithChildren = SponzoriRoute._addFileChildren(
  SponzoriRouteChildren,
)

interface TestZostavaIdRouteChildren {
  TestZostavaIdVysledkyRoute: typeof TestZostavaIdVysledkyRoute
}

const TestZostavaIdRouteChildren: TestZostavaIdRouteChildren = {
  TestZostavaIdVysledkyRoute: TestZostavaIdVysledkyRoute,
}

const TestZostavaIdRouteWithChildren = TestZostavaIdRoute._addFileChildren(
  TestZostavaIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  CookiesRoute: CookiesRoute,
  KontaktRoute: KontaktRoute,
  LoginRoute: LoginRoute,
  OProjekteRoute: OProjekteRoute,
  PodporaRoute: PodporaRoute,
  PrivacyRoute: PrivacyRoute,
  SkolyRoute: SkolyRoute,
  SponzoriRoute: SponzoriRouteWithChildren,
  SpravovatPodporuRoute: SpravovatPodporuRoute,
  ZmenyRoute: ZmenyRoute,
  PodakovanieSessionIdRoute: PodakovanieSessionIdRoute,
  RShareIdRoute: RShareIdRoute,
  SkoleniaSlugRoute: SkoleniaSlugRoute,
  TShareIdRoute: TShareIdRoute,
  TestZostavRoute: TestZostavRoute,
  TestySlugRoute: TestySlugRoute,
  SkoleniaIndexRoute: SkoleniaIndexRoute,
  TestIndexRoute: TestIndexRoute,
  TestyIndexRoute: TestyIndexRoute,
  TestZostavaIdRoute: TestZostavaIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
