/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SchoolsRouteImport } from './routes/schools'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ManageSupportRouteImport } from './routes/manage-support'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestsIndexRouteImport } from './routes/tests.index'
import { Route as TestIndexRouteImport } from './routes/test.index'
import { Route as SponsorsIndexRouteImport } from './routes/sponsors.index'
import { Route as SablonyIndexRouteImport } from './routes/sablony.index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as ContactFormIndexRouteImport } from './routes/contact-form.index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ThankYouSessionIdRouteImport } from './routes/thank-you.$sessionId'
import { Route as TestsSlugRouteImport } from './routes/tests.$slug'
import { Route as TestBuilderRouteImport } from './routes/test.builder'
import { Route as TShareIdRouteImport } from './routes/t.$shareId'
import { Route as SponsorsAllRouteImport } from './routes/sponsors.all'
import { Route as SchoolsDpaRouteImport } from './routes/schools_.dpa'
import { Route as SablonySlugRouteImport } from './routes/sablony.$slug'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as RShareIdRouteImport } from './routes/r.$shareId'
import { Route as LoginVerify2faRouteImport } from './routes/login_.verify-2fa'
import { Route as LoginEnroll2faRouteImport } from './routes/login_.enroll-2fa'
import { Route as DocsAppRouteImport } from './routes/docs.app'
import { Route as DocsAdminRouteImport } from './routes/docs.admin'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppTemplatesRouteImport } from './routes/app.templates'
import { Route as AppTeamsRouteImport } from './routes/app.teams'
import { Route as AppRetestRouteImport } from './routes/app.retest'
import { Route as AppRecommendationsRouteImport } from './routes/app.recommendations'
import { Route as AppPeerRouteImport } from './routes/app.peer'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppLibraryRouteImport } from './routes/app.library'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppHelpRouteImport } from './routes/app.help'
import { Route as AppDigestRouteImport } from './routes/app.digest'
import { Route as AppAudiencesRouteImport } from './routes/app.audiences'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTrainingsRouteImport } from './routes/admin/trainings'
import { Route as AdminTicketsRouteImport } from './routes/admin/tickets'
import { Route as AdminTestsRouteImport } from './routes/admin/tests'
import { Route as AdminTemplatesRouteImport } from './routes/admin/templates'
import { Route as AdminSupportRouteImport } from './routes/admin/support'
import { Route as AdminShareCardRouteImport } from './routes/admin/share-card'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSecurityRouteImport } from './routes/admin/security'
import { Route as AdminRespondentsRouteImport } from './routes/admin/respondents'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminQuickTestRouteImport } from './routes/admin/quick-test'
import { Route as AdminQuestionsRouteImport } from './routes/admin/questions'
import { Route as AdminPagesRouteImport } from './routes/admin/pages'
import { Route as AdminNavigationRouteImport } from './routes/admin/navigation'
import { Route as AdminHeaderRouteImport } from './routes/admin/header'
import { Route as AdminFooterRouteImport } from './routes/admin/footer'
import { Route as AdminDsrRouteImport } from './routes/admin/dsr'
import { Route as AdminDpaRequestsRouteImport } from './routes/admin/dpa-requests'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminAnswerSetsRouteImport } from './routes/admin/answer-sets'
import { Route as TestBuilderIndexRouteImport } from './routes/test.builder.index'
import { Route as AppTestsIndexRouteImport } from './routes/app.tests.index'
import { Route as AppEduTestsIndexRouteImport } from './routes/app.edu-tests.index'
import { Route as AdminTestsIndexRouteImport } from './routes/admin/tests.index'
import { Route as AdminPagesIndexRouteImport } from './routes/admin/pages.index'
import { Route as AdminBlogIndexRouteImport } from './routes/admin/blog/index'
import { Route as AdminAnswerSetsIndexRouteImport } from './routes/admin/answer-sets.index'
import { Route as TestBuilderIdRouteImport } from './routes/test.builder.$id'
import { Route as DocsAppSlugRouteImport } from './routes/docs.app.$slug'
import { Route as DocsAdminSlugRouteImport } from './routes/docs.admin.$slug'
import { Route as ContactFormTicketIdRouteImport } from './routes/contact-form.ticket.$id'
import { Route as BlogKategoriaSlugRouteImport } from './routes/blog/kategoria/$slug'
import { Route as BlogAutorSlugRouteImport } from './routes/blog/autor/$slug'
import { Route as AppTestsNewRouteImport } from './routes/app.tests.new'
import { Route as AppTestsTestIdRouteImport } from './routes/app.tests.$testId'
import { Route as AppSetsSetIdRouteImport } from './routes/app.sets.$setId'
import { Route as AppLegalDsrRouteImport } from './routes/app.legal.dsr'
import { Route as AppHelpContactRouteImport } from './routes/app.help.contact'
import { Route as AppAccountSecurityRouteImport } from './routes/app.account.security'
import { Route as AppAccountProfileRouteImport } from './routes/app.account.profile'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users.$userId'
import { Route as AdminTicketsTicketIdRouteImport } from './routes/admin/tickets.$ticketId'
import { Route as AdminTestsTestIdRouteImport } from './routes/admin/tests.$testId'
import { Route as AdminSettingsNotificationsRouteImport } from './routes/admin/settings.notifications'
import { Route as AdminPagesPageIdRouteImport } from './routes/admin/pages.$pageId'
import { Route as AdminBlogNewRouteImport } from './routes/admin/blog/new'
import { Route as AdminBlogIdRouteImport } from './routes/admin/blog/$id'
import { Route as AdminAnswerSetsSetIdRouteImport } from './routes/admin/answer-sets.$setId'
import { Route as TestBuilderIdIndexRouteImport } from './routes/test.builder.$id.index'
import { Route as TestBuilderIdResultsRouteImport } from './routes/test.builder.$id.results'
import { Route as TestBuilderIdResultsAttemptIdRouteImport } from './routes/test.builder.$id.results.$attemptId'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/support.lazy').then((d) => d.Route))
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsRoute = SchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/privacy.lazy').then((d) => d.Route))
const ManageSupportRoute = ManageSupportRouteImport.update({
  id: '/manage-support',
  path: '/manage-support',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/cookies.lazy').then((d) => d.Route))
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsIndexRoute = TestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsIndexRoute = SponsorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SponsorsRoute,
} as any)
const SablonyIndexRoute = SablonyIndexRouteImport.update({
  id: '/sablony/',
  path: '/sablony/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/sablony.index.lazy').then((d) => d.Route))
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactFormIndexRoute = ContactFormIndexRouteImport.update({
  id: '/contact-form/',
  path: '/contact-form/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/blog/index.lazy').then((d) => d.Route))
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin/index.lazy').then((d) => d.Route))
const ThankYouSessionIdRoute = ThankYouSessionIdRouteImport.update({
  id: '/thank-you/$sessionId',
  path: '/thank-you/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/thank-you.$sessionId.lazy').then((d) => d.Route),
)
const TestsSlugRoute = TestsSlugRouteImport.update({
  id: '/tests/$slug',
  path: '/tests/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TestBuilderRoute = TestBuilderRouteImport.update({
  id: '/test/builder',
  path: '/test/builder',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/test.builder.lazy').then((d) => d.Route))
const TShareIdRoute = TShareIdRouteImport.update({
  id: '/t/$shareId',
  path: '/t/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsAllRoute = SponsorsAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => SponsorsRoute,
} as any)
const SchoolsDpaRoute = SchoolsDpaRouteImport.update({
  id: '/schools_/dpa',
  path: '/schools/dpa',
  getParentRoute: () => rootRouteImport,
} as any)
const SablonySlugRoute = SablonySlugRouteImport.update({
  id: '/sablony/$slug',
  path: '/sablony/$slug',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/sablony.$slug.lazy').then((d) => d.Route))
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RShareIdRoute = RShareIdRouteImport.update({
  id: '/r/$shareId',
  path: '/r/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginVerify2faRoute = LoginVerify2faRouteImport.update({
  id: '/login_/verify-2fa',
  path: '/login/verify-2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginEnroll2faRoute = LoginEnroll2faRouteImport.update({
  id: '/login_/enroll-2fa',
  path: '/login/enroll-2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsAppRoute = DocsAppRouteImport.update({
  id: '/docs/app',
  path: '/docs/app',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsAdminRoute = DocsAdminRouteImport.update({
  id: '/docs/admin',
  path: '/docs/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/blog/$slug.lazy').then((d) => d.Route))
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsRoute = AppTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AppRoute,
} as any)
const AppRetestRoute = AppRetestRouteImport.update({
  id: '/retest',
  path: '/retest',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/app.retest.lazy').then((d) => d.Route))
const AppRecommendationsRoute = AppRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/app.recommendations.lazy').then((d) => d.Route),
)
const AppPeerRoute = AppPeerRouteImport.update({
  id: '/peer',
  path: '/peer',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/app.peer.lazy').then((d) => d.Route))
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/app.onboarding.lazy').then((d) => d.Route),
)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppDigestRoute = AppDigestRouteImport.update({
  id: '/digest',
  path: '/digest',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/app.digest.lazy').then((d) => d.Route))
const AppAudiencesRoute = AppAudiencesRouteImport.update({
  id: '/audiences',
  path: '/audiences',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin/users.lazy').then((d) => d.Route))
const AdminTrainingsRoute = AdminTrainingsRouteImport.update({
  id: '/trainings',
  path: '/trainings',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/trainings.lazy').then((d) => d.Route),
)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin/tickets.lazy').then((d) => d.Route))
const AdminTestsRoute = AdminTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/templates.lazy').then((d) => d.Route),
)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin/support.lazy').then((d) => d.Route))
const AdminShareCardRoute = AdminShareCardRouteImport.update({
  id: '/share-card',
  path: '/share-card',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/share-card.lazy').then((d) => d.Route),
)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/settings.lazy').then((d) => d.Route),
)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/security.lazy').then((d) => d.Route),
)
const AdminRespondentsRoute = AdminRespondentsRouteImport.update({
  id: '/respondents',
  path: '/respondents',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/respondents.lazy').then((d) => d.Route),
)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin/reports.lazy').then((d) => d.Route))
const AdminQuickTestRoute = AdminQuickTestRouteImport.update({
  id: '/quick-test',
  path: '/quick-test',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/quick-test.lazy').then((d) => d.Route),
)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/questions.lazy').then((d) => d.Route),
)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNavigationRoute = AdminNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/navigation.lazy').then((d) => d.Route),
)
const AdminHeaderRoute = AdminHeaderRouteImport.update({
  id: '/header',
  path: '/header',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin/header.lazy').then((d) => d.Route))
const AdminFooterRoute = AdminFooterRouteImport.update({
  id: '/footer',
  path: '/footer',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin/footer.lazy').then((d) => d.Route))
const AdminDsrRoute = AdminDsrRouteImport.update({
  id: '/dsr',
  path: '/dsr',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin/dsr.lazy').then((d) => d.Route))
const AdminDpaRequestsRoute = AdminDpaRequestsRouteImport.update({
  id: '/dpa-requests',
  path: '/dpa-requests',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/dpa-requests.lazy').then((d) => d.Route),
)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/categories.lazy').then((d) => d.Route),
)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin/audit.lazy').then((d) => d.Route))
const AdminAnswerSetsRoute = AdminAnswerSetsRouteImport.update({
  id: '/answer-sets',
  path: '/answer-sets',
  getParentRoute: () => AdminRoute,
} as any)
const TestBuilderIndexRoute = TestBuilderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TestBuilderRoute,
} as any).lazy(() =>
  import('./routes/test.builder.index.lazy').then((d) => d.Route),
)
const AppTestsIndexRoute = AppTestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => AppRoute,
} as any)
const AppEduTestsIndexRoute = AppEduTestsIndexRouteImport.update({
  id: '/edu-tests/',
  path: '/edu-tests/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/app.edu-tests.index.lazy').then((d) => d.Route),
)
const AdminTestsIndexRoute = AdminTestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminTestsRoute,
} as any).lazy(() =>
  import('./routes/admin/tests.index.lazy').then((d) => d.Route),
)
const AdminPagesIndexRoute = AdminPagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPagesRoute,
} as any).lazy(() =>
  import('./routes/admin/pages.index.lazy').then((d) => d.Route),
)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/blog/index.lazy').then((d) => d.Route),
)
const AdminAnswerSetsIndexRoute = AdminAnswerSetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAnswerSetsRoute,
} as any).lazy(() =>
  import('./routes/admin/answer-sets.index.lazy').then((d) => d.Route),
)
const TestBuilderIdRoute = TestBuilderIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TestBuilderRoute,
} as any).lazy(() =>
  import('./routes/test.builder.$id.lazy').then((d) => d.Route),
)
const DocsAppSlugRoute = DocsAppSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsAppRoute,
} as any)
const DocsAdminSlugRoute = DocsAdminSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsAdminRoute,
} as any)
const ContactFormTicketIdRoute = ContactFormTicketIdRouteImport.update({
  id: '/contact-form/ticket/$id',
  path: '/contact-form/ticket/$id',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/contact-form.ticket.$id.lazy').then((d) => d.Route),
)
const BlogKategoriaSlugRoute = BlogKategoriaSlugRouteImport.update({
  id: '/blog/kategoria/$slug',
  path: '/blog/kategoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/blog/kategoria/$slug.lazy').then((d) => d.Route),
)
const BlogAutorSlugRoute = BlogAutorSlugRouteImport.update({
  id: '/blog/autor/$slug',
  path: '/blog/autor/$slug',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/blog/autor/$slug.lazy').then((d) => d.Route),
)
const AppTestsNewRoute = AppTestsNewRouteImport.update({
  id: '/tests/new',
  path: '/tests/new',
  getParentRoute: () => AppRoute,
} as any)
const AppTestsTestIdRoute = AppTestsTestIdRouteImport.update({
  id: '/tests/$testId',
  path: '/tests/$testId',
  getParentRoute: () => AppRoute,
} as any)
const AppSetsSetIdRoute = AppSetsSetIdRouteImport.update({
  id: '/sets/$setId',
  path: '/sets/$setId',
  getParentRoute: () => AppRoute,
} as any)
const AppLegalDsrRoute = AppLegalDsrRouteImport.update({
  id: '/legal/dsr',
  path: '/legal/dsr',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpContactRoute = AppHelpContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppHelpRoute,
} as any)
const AppAccountSecurityRoute = AppAccountSecurityRouteImport.update({
  id: '/account/security',
  path: '/account/security',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountProfileRoute = AppAccountProfileRouteImport.update({
  id: '/account/profile',
  path: '/account/profile',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsersRoute,
} as any).lazy(() =>
  import('./routes/admin/users.$userId.lazy').then((d) => d.Route),
)
const AdminTicketsTicketIdRoute = AdminTicketsTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => AdminTicketsRoute,
} as any).lazy(() =>
  import('./routes/admin/tickets.$ticketId.lazy').then((d) => d.Route),
)
const AdminTestsTestIdRoute = AdminTestsTestIdRouteImport.update({
  id: '/$testId',
  path: '/$testId',
  getParentRoute: () => AdminTestsRoute,
} as any).lazy(() =>
  import('./routes/admin/tests.$testId.lazy').then((d) => d.Route),
)
const AdminSettingsNotificationsRoute =
  AdminSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AdminSettingsRoute,
  } as any).lazy(() =>
    import('./routes/admin/settings.notifications.lazy').then((d) => d.Route),
  )
const AdminPagesPageIdRoute = AdminPagesPageIdRouteImport.update({
  id: '/$pageId',
  path: '/$pageId',
  getParentRoute: () => AdminPagesRoute,
} as any).lazy(() =>
  import('./routes/admin/pages.$pageId.lazy').then((d) => d.Route),
)
const AdminBlogNewRoute = AdminBlogNewRouteImport.update({
  id: '/blog/new',
  path: '/blog/new',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/blog/new.lazy').then((d) => d.Route),
)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/blog/$id.lazy').then((d) => d.Route),
)
const AdminAnswerSetsSetIdRoute = AdminAnswerSetsSetIdRouteImport.update({
  id: '/$setId',
  path: '/$setId',
  getParentRoute: () => AdminAnswerSetsRoute,
} as any).lazy(() =>
  import('./routes/admin/answer-sets.$setId.lazy').then((d) => d.Route),
)
const TestBuilderIdIndexRoute = TestBuilderIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TestBuilderIdRoute,
} as any).lazy(() =>
  import('./routes/test.builder.$id.index.lazy').then((d) => d.Route),
)
const TestBuilderIdResultsRoute = TestBuilderIdResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => TestBuilderIdRoute,
} as any).lazy(() =>
  import('./routes/test.builder.$id.results.lazy').then((d) => d.Route),
)
const TestBuilderIdResultsAttemptIdRoute =
  TestBuilderIdResultsAttemptIdRouteImport.update({
    id: '/$attemptId',
    path: '/$attemptId',
    getParentRoute: () => TestBuilderIdResultsRoute,
  } as any).lazy(() =>
    import('./routes/test.builder.$id.results.$attemptId.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/manage-support': typeof ManageSupportRoute
  '/privacy': typeof PrivacyRoute
  '/schools': typeof SchoolsRoute
  '/signup': typeof SignupRoute
  '/sponsors': typeof SponsorsRouteWithChildren
  '/support': typeof SupportRoute
  '/admin/answer-sets': typeof AdminAnswerSetsRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dpa-requests': typeof AdminDpaRequestsRoute
  '/admin/dsr': typeof AdminDsrRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/header': typeof AdminHeaderRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/quick-test': typeof AdminQuickTestRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/respondents': typeof AdminRespondentsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRouteWithChildren
  '/admin/share-card': typeof AdminShareCardRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/tests': typeof AdminTestsRouteWithChildren
  '/admin/tickets': typeof AdminTicketsRouteWithChildren
  '/admin/trainings': typeof AdminTrainingsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/app/audiences': typeof AppAudiencesRoute
  '/app/digest': typeof AppDigestRoute
  '/app/help': typeof AppHelpRouteWithChildren
  '/app/history': typeof AppHistoryRoute
  '/app/library': typeof AppLibraryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/peer': typeof AppPeerRoute
  '/app/recommendations': typeof AppRecommendationsRoute
  '/app/retest': typeof AppRetestRoute
  '/app/teams': typeof AppTeamsRoute
  '/app/templates': typeof AppTemplatesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/docs/admin': typeof DocsAdminRouteWithChildren
  '/docs/app': typeof DocsAppRouteWithChildren
  '/login/enroll-2fa': typeof LoginEnroll2faRoute
  '/login/verify-2fa': typeof LoginVerify2faRoute
  '/r/$shareId': typeof RShareIdRoute
  '/s/$slug': typeof SSlugRoute
  '/sablony/$slug': typeof SablonySlugRoute
  '/schools/dpa': typeof SchoolsDpaRoute
  '/sponsors/all': typeof SponsorsAllRoute
  '/t/$shareId': typeof TShareIdRoute
  '/test/builder': typeof TestBuilderRouteWithChildren
  '/tests/$slug': typeof TestsSlugRoute
  '/thank-you/$sessionId': typeof ThankYouSessionIdRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/contact-form/': typeof ContactFormIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/sablony/': typeof SablonyIndexRoute
  '/sponsors/': typeof SponsorsIndexRoute
  '/test/': typeof TestIndexRoute
  '/tests/': typeof TestsIndexRoute
  '/admin/answer-sets/$setId': typeof AdminAnswerSetsSetIdRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/pages/$pageId': typeof AdminPagesPageIdRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/admin/tests/$testId': typeof AdminTestsTestIdRoute
  '/admin/tickets/$ticketId': typeof AdminTicketsTicketIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/app/account/profile': typeof AppAccountProfileRoute
  '/app/account/security': typeof AppAccountSecurityRoute
  '/app/help/contact': typeof AppHelpContactRoute
  '/app/legal/dsr': typeof AppLegalDsrRoute
  '/app/sets/$setId': typeof AppSetsSetIdRoute
  '/app/tests/$testId': typeof AppTestsTestIdRoute
  '/app/tests/new': typeof AppTestsNewRoute
  '/blog/autor/$slug': typeof BlogAutorSlugRoute
  '/blog/kategoria/$slug': typeof BlogKategoriaSlugRoute
  '/contact-form/ticket/$id': typeof ContactFormTicketIdRoute
  '/docs/admin/$slug': typeof DocsAdminSlugRoute
  '/docs/app/$slug': typeof DocsAppSlugRoute
  '/test/builder/$id': typeof TestBuilderIdRouteWithChildren
  '/admin/answer-sets/': typeof AdminAnswerSetsIndexRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
  '/admin/tests/': typeof AdminTestsIndexRoute
  '/app/edu-tests/': typeof AppEduTestsIndexRoute
  '/app/tests/': typeof AppTestsIndexRoute
  '/test/builder/': typeof TestBuilderIndexRoute
  '/test/builder/$id/results': typeof TestBuilderIdResultsRouteWithChildren
  '/test/builder/$id/': typeof TestBuilderIdIndexRoute
  '/test/builder/$id/results/$attemptId': typeof TestBuilderIdResultsAttemptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/manage-support': typeof ManageSupportRoute
  '/privacy': typeof PrivacyRoute
  '/schools': typeof SchoolsRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dpa-requests': typeof AdminDpaRequestsRoute
  '/admin/dsr': typeof AdminDsrRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/header': typeof AdminHeaderRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/quick-test': typeof AdminQuickTestRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/respondents': typeof AdminRespondentsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRouteWithChildren
  '/admin/share-card': typeof AdminShareCardRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/tickets': typeof AdminTicketsRouteWithChildren
  '/admin/trainings': typeof AdminTrainingsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/app/audiences': typeof AppAudiencesRoute
  '/app/digest': typeof AppDigestRoute
  '/app/help': typeof AppHelpRouteWithChildren
  '/app/history': typeof AppHistoryRoute
  '/app/library': typeof AppLibraryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/peer': typeof AppPeerRoute
  '/app/recommendations': typeof AppRecommendationsRoute
  '/app/retest': typeof AppRetestRoute
  '/app/teams': typeof AppTeamsRoute
  '/app/templates': typeof AppTemplatesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/docs/admin': typeof DocsAdminRouteWithChildren
  '/docs/app': typeof DocsAppRouteWithChildren
  '/login/enroll-2fa': typeof LoginEnroll2faRoute
  '/login/verify-2fa': typeof LoginVerify2faRoute
  '/r/$shareId': typeof RShareIdRoute
  '/s/$slug': typeof SSlugRoute
  '/sablony/$slug': typeof SablonySlugRoute
  '/schools/dpa': typeof SchoolsDpaRoute
  '/sponsors/all': typeof SponsorsAllRoute
  '/t/$shareId': typeof TShareIdRoute
  '/tests/$slug': typeof TestsSlugRoute
  '/thank-you/$sessionId': typeof ThankYouSessionIdRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/blog': typeof BlogIndexRoute
  '/contact-form': typeof ContactFormIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/sablony': typeof SablonyIndexRoute
  '/sponsors': typeof SponsorsIndexRoute
  '/test': typeof TestIndexRoute
  '/tests': typeof TestsIndexRoute
  '/admin/answer-sets/$setId': typeof AdminAnswerSetsSetIdRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/pages/$pageId': typeof AdminPagesPageIdRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/admin/tests/$testId': typeof AdminTestsTestIdRoute
  '/admin/tickets/$ticketId': typeof AdminTicketsTicketIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/app/account/profile': typeof AppAccountProfileRoute
  '/app/account/security': typeof AppAccountSecurityRoute
  '/app/help/contact': typeof AppHelpContactRoute
  '/app/legal/dsr': typeof AppLegalDsrRoute
  '/app/sets/$setId': typeof AppSetsSetIdRoute
  '/app/tests/$testId': typeof AppTestsTestIdRoute
  '/app/tests/new': typeof AppTestsNewRoute
  '/blog/autor/$slug': typeof BlogAutorSlugRoute
  '/blog/kategoria/$slug': typeof BlogKategoriaSlugRoute
  '/contact-form/ticket/$id': typeof ContactFormTicketIdRoute
  '/docs/admin/$slug': typeof DocsAdminSlugRoute
  '/docs/app/$slug': typeof DocsAppSlugRoute
  '/admin/answer-sets': typeof AdminAnswerSetsIndexRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/pages': typeof AdminPagesIndexRoute
  '/admin/tests': typeof AdminTestsIndexRoute
  '/app/edu-tests': typeof AppEduTestsIndexRoute
  '/app/tests': typeof AppTestsIndexRoute
  '/test/builder': typeof TestBuilderIndexRoute
  '/test/builder/$id/results': typeof TestBuilderIdResultsRouteWithChildren
  '/test/builder/$id': typeof TestBuilderIdIndexRoute
  '/test/builder/$id/results/$attemptId': typeof TestBuilderIdResultsAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/manage-support': typeof ManageSupportRoute
  '/privacy': typeof PrivacyRoute
  '/schools': typeof SchoolsRoute
  '/signup': typeof SignupRoute
  '/sponsors': typeof SponsorsRouteWithChildren
  '/support': typeof SupportRoute
  '/admin/answer-sets': typeof AdminAnswerSetsRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dpa-requests': typeof AdminDpaRequestsRoute
  '/admin/dsr': typeof AdminDsrRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/header': typeof AdminHeaderRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/quick-test': typeof AdminQuickTestRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/respondents': typeof AdminRespondentsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRouteWithChildren
  '/admin/share-card': typeof AdminShareCardRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/tests': typeof AdminTestsRouteWithChildren
  '/admin/tickets': typeof AdminTicketsRouteWithChildren
  '/admin/trainings': typeof AdminTrainingsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/app/audiences': typeof AppAudiencesRoute
  '/app/digest': typeof AppDigestRoute
  '/app/help': typeof AppHelpRouteWithChildren
  '/app/history': typeof AppHistoryRoute
  '/app/library': typeof AppLibraryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/peer': typeof AppPeerRoute
  '/app/recommendations': typeof AppRecommendationsRoute
  '/app/retest': typeof AppRetestRoute
  '/app/teams': typeof AppTeamsRoute
  '/app/templates': typeof AppTemplatesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/docs/admin': typeof DocsAdminRouteWithChildren
  '/docs/app': typeof DocsAppRouteWithChildren
  '/login_/enroll-2fa': typeof LoginEnroll2faRoute
  '/login_/verify-2fa': typeof LoginVerify2faRoute
  '/r/$shareId': typeof RShareIdRoute
  '/s/$slug': typeof SSlugRoute
  '/sablony/$slug': typeof SablonySlugRoute
  '/schools_/dpa': typeof SchoolsDpaRoute
  '/sponsors/all': typeof SponsorsAllRoute
  '/t/$shareId': typeof TShareIdRoute
  '/test/builder': typeof TestBuilderRouteWithChildren
  '/tests/$slug': typeof TestsSlugRoute
  '/thank-you/$sessionId': typeof ThankYouSessionIdRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/contact-form/': typeof ContactFormIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/sablony/': typeof SablonyIndexRoute
  '/sponsors/': typeof SponsorsIndexRoute
  '/test/': typeof TestIndexRoute
  '/tests/': typeof TestsIndexRoute
  '/admin/answer-sets/$setId': typeof AdminAnswerSetsSetIdRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/pages/$pageId': typeof AdminPagesPageIdRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/admin/tests/$testId': typeof AdminTestsTestIdRoute
  '/admin/tickets/$ticketId': typeof AdminTicketsTicketIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/app/account/profile': typeof AppAccountProfileRoute
  '/app/account/security': typeof AppAccountSecurityRoute
  '/app/help/contact': typeof AppHelpContactRoute
  '/app/legal/dsr': typeof AppLegalDsrRoute
  '/app/sets/$setId': typeof AppSetsSetIdRoute
  '/app/tests/$testId': typeof AppTestsTestIdRoute
  '/app/tests/new': typeof AppTestsNewRoute
  '/blog/autor/$slug': typeof BlogAutorSlugRoute
  '/blog/kategoria/$slug': typeof BlogKategoriaSlugRoute
  '/contact-form/ticket/$id': typeof ContactFormTicketIdRoute
  '/docs/admin/$slug': typeof DocsAdminSlugRoute
  '/docs/app/$slug': typeof DocsAppSlugRoute
  '/test/builder/$id': typeof TestBuilderIdRouteWithChildren
  '/admin/answer-sets/': typeof AdminAnswerSetsIndexRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
  '/admin/tests/': typeof AdminTestsIndexRoute
  '/app/edu-tests/': typeof AppEduTestsIndexRoute
  '/app/tests/': typeof AppTestsIndexRoute
  '/test/builder/': typeof TestBuilderIndexRoute
  '/test/builder/$id/results': typeof TestBuilderIdResultsRouteWithChildren
  '/test/builder/$id/': typeof TestBuilderIdIndexRoute
  '/test/builder/$id/results/$attemptId': typeof TestBuilderIdResultsAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/changelog'
    | '/contact'
    | '/cookies'
    | '/forgot-password'
    | '/login'
    | '/manage-support'
    | '/privacy'
    | '/schools'
    | '/signup'
    | '/sponsors'
    | '/support'
    | '/admin/answer-sets'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/dpa-requests'
    | '/admin/dsr'
    | '/admin/footer'
    | '/admin/header'
    | '/admin/navigation'
    | '/admin/pages'
    | '/admin/questions'
    | '/admin/quick-test'
    | '/admin/reports'
    | '/admin/respondents'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/share-card'
    | '/admin/support'
    | '/admin/templates'
    | '/admin/tests'
    | '/admin/tickets'
    | '/admin/trainings'
    | '/admin/users'
    | '/app/audiences'
    | '/app/digest'
    | '/app/help'
    | '/app/history'
    | '/app/library'
    | '/app/notifications'
    | '/app/onboarding'
    | '/app/peer'
    | '/app/recommendations'
    | '/app/retest'
    | '/app/teams'
    | '/app/templates'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/docs/admin'
    | '/docs/app'
    | '/login/enroll-2fa'
    | '/login/verify-2fa'
    | '/r/$shareId'
    | '/s/$slug'
    | '/sablony/$slug'
    | '/schools/dpa'
    | '/sponsors/all'
    | '/t/$shareId'
    | '/test/builder'
    | '/tests/$slug'
    | '/thank-you/$sessionId'
    | '/admin/'
    | '/app/'
    | '/blog/'
    | '/contact-form/'
    | '/courses/'
    | '/sablony/'
    | '/sponsors/'
    | '/test/'
    | '/tests/'
    | '/admin/answer-sets/$setId'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/admin/pages/$pageId'
    | '/admin/settings/notifications'
    | '/admin/tests/$testId'
    | '/admin/tickets/$ticketId'
    | '/admin/users/$userId'
    | '/app/account/profile'
    | '/app/account/security'
    | '/app/help/contact'
    | '/app/legal/dsr'
    | '/app/sets/$setId'
    | '/app/tests/$testId'
    | '/app/tests/new'
    | '/blog/autor/$slug'
    | '/blog/kategoria/$slug'
    | '/contact-form/ticket/$id'
    | '/docs/admin/$slug'
    | '/docs/app/$slug'
    | '/test/builder/$id'
    | '/admin/answer-sets/'
    | '/admin/blog/'
    | '/admin/pages/'
    | '/admin/tests/'
    | '/app/edu-tests/'
    | '/app/tests/'
    | '/test/builder/'
    | '/test/builder/$id/results'
    | '/test/builder/$id/'
    | '/test/builder/$id/results/$attemptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/changelog'
    | '/contact'
    | '/cookies'
    | '/forgot-password'
    | '/login'
    | '/manage-support'
    | '/privacy'
    | '/schools'
    | '/signup'
    | '/support'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/dpa-requests'
    | '/admin/dsr'
    | '/admin/footer'
    | '/admin/header'
    | '/admin/navigation'
    | '/admin/questions'
    | '/admin/quick-test'
    | '/admin/reports'
    | '/admin/respondents'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/share-card'
    | '/admin/support'
    | '/admin/templates'
    | '/admin/tickets'
    | '/admin/trainings'
    | '/admin/users'
    | '/app/audiences'
    | '/app/digest'
    | '/app/help'
    | '/app/history'
    | '/app/library'
    | '/app/notifications'
    | '/app/onboarding'
    | '/app/peer'
    | '/app/recommendations'
    | '/app/retest'
    | '/app/teams'
    | '/app/templates'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/docs/admin'
    | '/docs/app'
    | '/login/enroll-2fa'
    | '/login/verify-2fa'
    | '/r/$shareId'
    | '/s/$slug'
    | '/sablony/$slug'
    | '/schools/dpa'
    | '/sponsors/all'
    | '/t/$shareId'
    | '/tests/$slug'
    | '/thank-you/$sessionId'
    | '/admin'
    | '/app'
    | '/blog'
    | '/contact-form'
    | '/courses'
    | '/sablony'
    | '/sponsors'
    | '/test'
    | '/tests'
    | '/admin/answer-sets/$setId'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/admin/pages/$pageId'
    | '/admin/settings/notifications'
    | '/admin/tests/$testId'
    | '/admin/tickets/$ticketId'
    | '/admin/users/$userId'
    | '/app/account/profile'
    | '/app/account/security'
    | '/app/help/contact'
    | '/app/legal/dsr'
    | '/app/sets/$setId'
    | '/app/tests/$testId'
    | '/app/tests/new'
    | '/blog/autor/$slug'
    | '/blog/kategoria/$slug'
    | '/contact-form/ticket/$id'
    | '/docs/admin/$slug'
    | '/docs/app/$slug'
    | '/admin/answer-sets'
    | '/admin/blog'
    | '/admin/pages'
    | '/admin/tests'
    | '/app/edu-tests'
    | '/app/tests'
    | '/test/builder'
    | '/test/builder/$id/results'
    | '/test/builder/$id'
    | '/test/builder/$id/results/$attemptId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/changelog'
    | '/contact'
    | '/cookies'
    | '/forgot-password'
    | '/login'
    | '/manage-support'
    | '/privacy'
    | '/schools'
    | '/signup'
    | '/sponsors'
    | '/support'
    | '/admin/answer-sets'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/dpa-requests'
    | '/admin/dsr'
    | '/admin/footer'
    | '/admin/header'
    | '/admin/navigation'
    | '/admin/pages'
    | '/admin/questions'
    | '/admin/quick-test'
    | '/admin/reports'
    | '/admin/respondents'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/share-card'
    | '/admin/support'
    | '/admin/templates'
    | '/admin/tests'
    | '/admin/tickets'
    | '/admin/trainings'
    | '/admin/users'
    | '/app/audiences'
    | '/app/digest'
    | '/app/help'
    | '/app/history'
    | '/app/library'
    | '/app/notifications'
    | '/app/onboarding'
    | '/app/peer'
    | '/app/recommendations'
    | '/app/retest'
    | '/app/teams'
    | '/app/templates'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/docs/admin'
    | '/docs/app'
    | '/login_/enroll-2fa'
    | '/login_/verify-2fa'
    | '/r/$shareId'
    | '/s/$slug'
    | '/sablony/$slug'
    | '/schools_/dpa'
    | '/sponsors/all'
    | '/t/$shareId'
    | '/test/builder'
    | '/tests/$slug'
    | '/thank-you/$sessionId'
    | '/admin/'
    | '/app/'
    | '/blog/'
    | '/contact-form/'
    | '/courses/'
    | '/sablony/'
    | '/sponsors/'
    | '/test/'
    | '/tests/'
    | '/admin/answer-sets/$setId'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/admin/pages/$pageId'
    | '/admin/settings/notifications'
    | '/admin/tests/$testId'
    | '/admin/tickets/$ticketId'
    | '/admin/users/$userId'
    | '/app/account/profile'
    | '/app/account/security'
    | '/app/help/contact'
    | '/app/legal/dsr'
    | '/app/sets/$setId'
    | '/app/tests/$testId'
    | '/app/tests/new'
    | '/blog/autor/$slug'
    | '/blog/kategoria/$slug'
    | '/contact-form/ticket/$id'
    | '/docs/admin/$slug'
    | '/docs/app/$slug'
    | '/test/builder/$id'
    | '/admin/answer-sets/'
    | '/admin/blog/'
    | '/admin/pages/'
    | '/admin/tests/'
    | '/app/edu-tests/'
    | '/app/tests/'
    | '/test/builder/'
    | '/test/builder/$id/results'
    | '/test/builder/$id/'
    | '/test/builder/$id/results/$attemptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ManageSupportRoute: typeof ManageSupportRoute
  PrivacyRoute: typeof PrivacyRoute
  SchoolsRoute: typeof SchoolsRoute
  SignupRoute: typeof SignupRoute
  SponsorsRoute: typeof SponsorsRouteWithChildren
  SupportRoute: typeof SupportRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  DocsAdminRoute: typeof DocsAdminRouteWithChildren
  DocsAppRoute: typeof DocsAppRouteWithChildren
  LoginEnroll2faRoute: typeof LoginEnroll2faRoute
  LoginVerify2faRoute: typeof LoginVerify2faRoute
  RShareIdRoute: typeof RShareIdRoute
  SSlugRoute: typeof SSlugRoute
  SablonySlugRoute: typeof SablonySlugRoute
  SchoolsDpaRoute: typeof SchoolsDpaRoute
  TShareIdRoute: typeof TShareIdRoute
  TestBuilderRoute: typeof TestBuilderRouteWithChildren
  TestsSlugRoute: typeof TestsSlugRoute
  ThankYouSessionIdRoute: typeof ThankYouSessionIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ContactFormIndexRoute: typeof ContactFormIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  SablonyIndexRoute: typeof SablonyIndexRoute
  TestIndexRoute: typeof TestIndexRoute
  TestsIndexRoute: typeof TestsIndexRoute
  BlogAutorSlugRoute: typeof BlogAutorSlugRoute
  BlogKategoriaSlugRoute: typeof BlogKategoriaSlugRoute
  ContactFormTicketIdRoute: typeof ContactFormTicketIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools': {
      id: '/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof SchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-support': {
      id: '/manage-support'
      path: '/manage-support'
      fullPath: '/manage-support'
      preLoaderRoute: typeof ManageSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/': {
      id: '/tests/'
      path: '/tests'
      fullPath: '/tests/'
      preLoaderRoute: typeof TestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors/': {
      id: '/sponsors/'
      path: '/'
      fullPath: '/sponsors/'
      preLoaderRoute: typeof SponsorsIndexRouteImport
      parentRoute: typeof SponsorsRoute
    }
    '/sablony/': {
      id: '/sablony/'
      path: '/sablony'
      fullPath: '/sablony/'
      preLoaderRoute: typeof SablonyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-form/': {
      id: '/contact-form/'
      path: '/contact-form'
      fullPath: '/contact-form/'
      preLoaderRoute: typeof ContactFormIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/thank-you/$sessionId': {
      id: '/thank-you/$sessionId'
      path: '/thank-you/$sessionId'
      fullPath: '/thank-you/$sessionId'
      preLoaderRoute: typeof ThankYouSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/$slug': {
      id: '/tests/$slug'
      path: '/tests/$slug'
      fullPath: '/tests/$slug'
      preLoaderRoute: typeof TestsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/builder': {
      id: '/test/builder'
      path: '/test/builder'
      fullPath: '/test/builder'
      preLoaderRoute: typeof TestBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$shareId': {
      id: '/t/$shareId'
      path: '/t/$shareId'
      fullPath: '/t/$shareId'
      preLoaderRoute: typeof TShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors/all': {
      id: '/sponsors/all'
      path: '/all'
      fullPath: '/sponsors/all'
      preLoaderRoute: typeof SponsorsAllRouteImport
      parentRoute: typeof SponsorsRoute
    }
    '/schools_/dpa': {
      id: '/schools_/dpa'
      path: '/schools/dpa'
      fullPath: '/schools/dpa'
      preLoaderRoute: typeof SchoolsDpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sablony/$slug': {
      id: '/sablony/$slug'
      path: '/sablony/$slug'
      fullPath: '/sablony/$slug'
      preLoaderRoute: typeof SablonySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$shareId': {
      id: '/r/$shareId'
      path: '/r/$shareId'
      fullPath: '/r/$shareId'
      preLoaderRoute: typeof RShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login_/verify-2fa': {
      id: '/login_/verify-2fa'
      path: '/login/verify-2fa'
      fullPath: '/login/verify-2fa'
      preLoaderRoute: typeof LoginVerify2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login_/enroll-2fa': {
      id: '/login_/enroll-2fa'
      path: '/login/enroll-2fa'
      fullPath: '/login/enroll-2fa'
      preLoaderRoute: typeof LoginEnroll2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/app': {
      id: '/docs/app'
      path: '/docs/app'
      fullPath: '/docs/app'
      preLoaderRoute: typeof DocsAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/admin': {
      id: '/docs/admin'
      path: '/docs/admin'
      fullPath: '/docs/admin'
      preLoaderRoute: typeof DocsAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/templates': {
      id: '/app/templates'
      path: '/templates'
      fullPath: '/app/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teams': {
      id: '/app/teams'
      path: '/teams'
      fullPath: '/app/teams'
      preLoaderRoute: typeof AppTeamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/retest': {
      id: '/app/retest'
      path: '/retest'
      fullPath: '/app/retest'
      preLoaderRoute: typeof AppRetestRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recommendations': {
      id: '/app/recommendations'
      path: '/recommendations'
      fullPath: '/app/recommendations'
      preLoaderRoute: typeof AppRecommendationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/peer': {
      id: '/app/peer'
      path: '/peer'
      fullPath: '/app/peer'
      preLoaderRoute: typeof AppPeerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library': {
      id: '/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/help': {
      id: '/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/digest': {
      id: '/app/digest'
      path: '/digest'
      fullPath: '/app/digest'
      preLoaderRoute: typeof AppDigestRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audiences': {
      id: '/app/audiences'
      path: '/audiences'
      fullPath: '/app/audiences'
      preLoaderRoute: typeof AppAudiencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/trainings': {
      id: '/admin/trainings'
      path: '/trainings'
      fullPath: '/admin/trainings'
      preLoaderRoute: typeof AdminTrainingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tests': {
      id: '/admin/tests'
      path: '/tests'
      fullPath: '/admin/tests'
      preLoaderRoute: typeof AdminTestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/share-card': {
      id: '/admin/share-card'
      path: '/share-card'
      fullPath: '/admin/share-card'
      preLoaderRoute: typeof AdminShareCardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/respondents': {
      id: '/admin/respondents'
      path: '/respondents'
      fullPath: '/admin/respondents'
      preLoaderRoute: typeof AdminRespondentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quick-test': {
      id: '/admin/quick-test'
      path: '/quick-test'
      fullPath: '/admin/quick-test'
      preLoaderRoute: typeof AdminQuickTestRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/navigation': {
      id: '/admin/navigation'
      path: '/navigation'
      fullPath: '/admin/navigation'
      preLoaderRoute: typeof AdminNavigationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/header': {
      id: '/admin/header'
      path: '/header'
      fullPath: '/admin/header'
      preLoaderRoute: typeof AdminHeaderRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/footer': {
      id: '/admin/footer'
      path: '/footer'
      fullPath: '/admin/footer'
      preLoaderRoute: typeof AdminFooterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dsr': {
      id: '/admin/dsr'
      path: '/dsr'
      fullPath: '/admin/dsr'
      preLoaderRoute: typeof AdminDsrRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dpa-requests': {
      id: '/admin/dpa-requests'
      path: '/dpa-requests'
      fullPath: '/admin/dpa-requests'
      preLoaderRoute: typeof AdminDpaRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/answer-sets': {
      id: '/admin/answer-sets'
      path: '/answer-sets'
      fullPath: '/admin/answer-sets'
      preLoaderRoute: typeof AdminAnswerSetsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/test/builder/': {
      id: '/test/builder/'
      path: '/'
      fullPath: '/test/builder/'
      preLoaderRoute: typeof TestBuilderIndexRouteImport
      parentRoute: typeof TestBuilderRoute
    }
    '/app/tests/': {
      id: '/app/tests/'
      path: '/tests'
      fullPath: '/app/tests/'
      preLoaderRoute: typeof AppTestsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/edu-tests/': {
      id: '/app/edu-tests/'
      path: '/edu-tests'
      fullPath: '/app/edu-tests/'
      preLoaderRoute: typeof AppEduTestsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/tests/': {
      id: '/admin/tests/'
      path: '/'
      fullPath: '/admin/tests/'
      preLoaderRoute: typeof AdminTestsIndexRouteImport
      parentRoute: typeof AdminTestsRoute
    }
    '/admin/pages/': {
      id: '/admin/pages/'
      path: '/'
      fullPath: '/admin/pages/'
      preLoaderRoute: typeof AdminPagesIndexRouteImport
      parentRoute: typeof AdminPagesRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/answer-sets/': {
      id: '/admin/answer-sets/'
      path: '/'
      fullPath: '/admin/answer-sets/'
      preLoaderRoute: typeof AdminAnswerSetsIndexRouteImport
      parentRoute: typeof AdminAnswerSetsRoute
    }
    '/test/builder/$id': {
      id: '/test/builder/$id'
      path: '/$id'
      fullPath: '/test/builder/$id'
      preLoaderRoute: typeof TestBuilderIdRouteImport
      parentRoute: typeof TestBuilderRoute
    }
    '/docs/app/$slug': {
      id: '/docs/app/$slug'
      path: '/$slug'
      fullPath: '/docs/app/$slug'
      preLoaderRoute: typeof DocsAppSlugRouteImport
      parentRoute: typeof DocsAppRoute
    }
    '/docs/admin/$slug': {
      id: '/docs/admin/$slug'
      path: '/$slug'
      fullPath: '/docs/admin/$slug'
      preLoaderRoute: typeof DocsAdminSlugRouteImport
      parentRoute: typeof DocsAdminRoute
    }
    '/contact-form/ticket/$id': {
      id: '/contact-form/ticket/$id'
      path: '/contact-form/ticket/$id'
      fullPath: '/contact-form/ticket/$id'
      preLoaderRoute: typeof ContactFormTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/kategoria/$slug': {
      id: '/blog/kategoria/$slug'
      path: '/blog/kategoria/$slug'
      fullPath: '/blog/kategoria/$slug'
      preLoaderRoute: typeof BlogKategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/autor/$slug': {
      id: '/blog/autor/$slug'
      path: '/blog/autor/$slug'
      fullPath: '/blog/autor/$slug'
      preLoaderRoute: typeof BlogAutorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tests/new': {
      id: '/app/tests/new'
      path: '/tests/new'
      fullPath: '/app/tests/new'
      preLoaderRoute: typeof AppTestsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tests/$testId': {
      id: '/app/tests/$testId'
      path: '/tests/$testId'
      fullPath: '/app/tests/$testId'
      preLoaderRoute: typeof AppTestsTestIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sets/$setId': {
      id: '/app/sets/$setId'
      path: '/sets/$setId'
      fullPath: '/app/sets/$setId'
      preLoaderRoute: typeof AppSetsSetIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/legal/dsr': {
      id: '/app/legal/dsr'
      path: '/legal/dsr'
      fullPath: '/app/legal/dsr'
      preLoaderRoute: typeof AppLegalDsrRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/help/contact': {
      id: '/app/help/contact'
      path: '/contact'
      fullPath: '/app/help/contact'
      preLoaderRoute: typeof AppHelpContactRouteImport
      parentRoute: typeof AppHelpRoute
    }
    '/app/account/security': {
      id: '/app/account/security'
      path: '/account/security'
      fullPath: '/app/account/security'
      preLoaderRoute: typeof AppAccountSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/account/profile': {
      id: '/app/account/profile'
      path: '/account/profile'
      fullPath: '/app/account/profile'
      preLoaderRoute: typeof AppAccountProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/tickets/$ticketId': {
      id: '/admin/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/admin/tickets/$ticketId'
      preLoaderRoute: typeof AdminTicketsTicketIdRouteImport
      parentRoute: typeof AdminTicketsRoute
    }
    '/admin/tests/$testId': {
      id: '/admin/tests/$testId'
      path: '/$testId'
      fullPath: '/admin/tests/$testId'
      preLoaderRoute: typeof AdminTestsTestIdRouteImport
      parentRoute: typeof AdminTestsRoute
    }
    '/admin/settings/notifications': {
      id: '/admin/settings/notifications'
      path: '/notifications'
      fullPath: '/admin/settings/notifications'
      preLoaderRoute: typeof AdminSettingsNotificationsRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/pages/$pageId': {
      id: '/admin/pages/$pageId'
      path: '/$pageId'
      fullPath: '/admin/pages/$pageId'
      preLoaderRoute: typeof AdminPagesPageIdRouteImport
      parentRoute: typeof AdminPagesRoute
    }
    '/admin/blog/new': {
      id: '/admin/blog/new'
      path: '/blog/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AdminBlogNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/answer-sets/$setId': {
      id: '/admin/answer-sets/$setId'
      path: '/$setId'
      fullPath: '/admin/answer-sets/$setId'
      preLoaderRoute: typeof AdminAnswerSetsSetIdRouteImport
      parentRoute: typeof AdminAnswerSetsRoute
    }
    '/test/builder/$id/': {
      id: '/test/builder/$id/'
      path: '/'
      fullPath: '/test/builder/$id/'
      preLoaderRoute: typeof TestBuilderIdIndexRouteImport
      parentRoute: typeof TestBuilderIdRoute
    }
    '/test/builder/$id/results': {
      id: '/test/builder/$id/results'
      path: '/results'
      fullPath: '/test/builder/$id/results'
      preLoaderRoute: typeof TestBuilderIdResultsRouteImport
      parentRoute: typeof TestBuilderIdRoute
    }
    '/test/builder/$id/results/$attemptId': {
      id: '/test/builder/$id/results/$attemptId'
      path: '/$attemptId'
      fullPath: '/test/builder/$id/results/$attemptId'
      preLoaderRoute: typeof TestBuilderIdResultsAttemptIdRouteImport
      parentRoute: typeof TestBuilderIdResultsRoute
    }
  }
}

interface AdminAnswerSetsRouteChildren {
  AdminAnswerSetsSetIdRoute: typeof AdminAnswerSetsSetIdRoute
  AdminAnswerSetsIndexRoute: typeof AdminAnswerSetsIndexRoute
}

const AdminAnswerSetsRouteChildren: AdminAnswerSetsRouteChildren = {
  AdminAnswerSetsSetIdRoute: AdminAnswerSetsSetIdRoute,
  AdminAnswerSetsIndexRoute: AdminAnswerSetsIndexRoute,
}

const AdminAnswerSetsRouteWithChildren = AdminAnswerSetsRoute._addFileChildren(
  AdminAnswerSetsRouteChildren,
)

interface AdminPagesRouteChildren {
  AdminPagesPageIdRoute: typeof AdminPagesPageIdRoute
  AdminPagesIndexRoute: typeof AdminPagesIndexRoute
}

const AdminPagesRouteChildren: AdminPagesRouteChildren = {
  AdminPagesPageIdRoute: AdminPagesPageIdRoute,
  AdminPagesIndexRoute: AdminPagesIndexRoute,
}

const AdminPagesRouteWithChildren = AdminPagesRoute._addFileChildren(
  AdminPagesRouteChildren,
)

interface AdminSettingsRouteChildren {
  AdminSettingsNotificationsRoute: typeof AdminSettingsNotificationsRoute
}

const AdminSettingsRouteChildren: AdminSettingsRouteChildren = {
  AdminSettingsNotificationsRoute: AdminSettingsNotificationsRoute,
}

const AdminSettingsRouteWithChildren = AdminSettingsRoute._addFileChildren(
  AdminSettingsRouteChildren,
)

interface AdminTestsRouteChildren {
  AdminTestsTestIdRoute: typeof AdminTestsTestIdRoute
  AdminTestsIndexRoute: typeof AdminTestsIndexRoute
}

const AdminTestsRouteChildren: AdminTestsRouteChildren = {
  AdminTestsTestIdRoute: AdminTestsTestIdRoute,
  AdminTestsIndexRoute: AdminTestsIndexRoute,
}

const AdminTestsRouteWithChildren = AdminTestsRoute._addFileChildren(
  AdminTestsRouteChildren,
)

interface AdminTicketsRouteChildren {
  AdminTicketsTicketIdRoute: typeof AdminTicketsTicketIdRoute
}

const AdminTicketsRouteChildren: AdminTicketsRouteChildren = {
  AdminTicketsTicketIdRoute: AdminTicketsTicketIdRoute,
}

const AdminTicketsRouteWithChildren = AdminTicketsRoute._addFileChildren(
  AdminTicketsRouteChildren,
)

interface AdminUsersRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminAnswerSetsRoute: typeof AdminAnswerSetsRouteWithChildren
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDpaRequestsRoute: typeof AdminDpaRequestsRoute
  AdminDsrRoute: typeof AdminDsrRoute
  AdminFooterRoute: typeof AdminFooterRoute
  AdminHeaderRoute: typeof AdminHeaderRoute
  AdminNavigationRoute: typeof AdminNavigationRoute
  AdminPagesRoute: typeof AdminPagesRouteWithChildren
  AdminQuestionsRoute: typeof AdminQuestionsRoute
  AdminQuickTestRoute: typeof AdminQuickTestRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRespondentsRoute: typeof AdminRespondentsRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSettingsRoute: typeof AdminSettingsRouteWithChildren
  AdminShareCardRoute: typeof AdminShareCardRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  AdminTestsRoute: typeof AdminTestsRouteWithChildren
  AdminTicketsRoute: typeof AdminTicketsRouteWithChildren
  AdminTrainingsRoute: typeof AdminTrainingsRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogIdRoute: typeof AdminBlogIdRoute
  AdminBlogNewRoute: typeof AdminBlogNewRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnswerSetsRoute: AdminAnswerSetsRouteWithChildren,
  AdminAuditRoute: AdminAuditRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminDpaRequestsRoute: AdminDpaRequestsRoute,
  AdminDsrRoute: AdminDsrRoute,
  AdminFooterRoute: AdminFooterRoute,
  AdminHeaderRoute: AdminHeaderRoute,
  AdminNavigationRoute: AdminNavigationRoute,
  AdminPagesRoute: AdminPagesRouteWithChildren,
  AdminQuestionsRoute: AdminQuestionsRoute,
  AdminQuickTestRoute: AdminQuickTestRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRespondentsRoute: AdminRespondentsRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSettingsRoute: AdminSettingsRouteWithChildren,
  AdminShareCardRoute: AdminShareCardRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
  AdminTestsRoute: AdminTestsRouteWithChildren,
  AdminTicketsRoute: AdminTicketsRouteWithChildren,
  AdminTrainingsRoute: AdminTrainingsRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogIdRoute: AdminBlogIdRoute,
  AdminBlogNewRoute: AdminBlogNewRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppHelpRouteChildren {
  AppHelpContactRoute: typeof AppHelpContactRoute
}

const AppHelpRouteChildren: AppHelpRouteChildren = {
  AppHelpContactRoute: AppHelpContactRoute,
}

const AppHelpRouteWithChildren =
  AppHelpRoute._addFileChildren(AppHelpRouteChildren)

interface AppRouteChildren {
  AppAudiencesRoute: typeof AppAudiencesRoute
  AppDigestRoute: typeof AppDigestRoute
  AppHelpRoute: typeof AppHelpRouteWithChildren
  AppHistoryRoute: typeof AppHistoryRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPeerRoute: typeof AppPeerRoute
  AppRecommendationsRoute: typeof AppRecommendationsRoute
  AppRetestRoute: typeof AppRetestRoute
  AppTeamsRoute: typeof AppTeamsRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAccountProfileRoute: typeof AppAccountProfileRoute
  AppAccountSecurityRoute: typeof AppAccountSecurityRoute
  AppLegalDsrRoute: typeof AppLegalDsrRoute
  AppSetsSetIdRoute: typeof AppSetsSetIdRoute
  AppTestsTestIdRoute: typeof AppTestsTestIdRoute
  AppTestsNewRoute: typeof AppTestsNewRoute
  AppEduTestsIndexRoute: typeof AppEduTestsIndexRoute
  AppTestsIndexRoute: typeof AppTestsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAudiencesRoute: AppAudiencesRoute,
  AppDigestRoute: AppDigestRoute,
  AppHelpRoute: AppHelpRouteWithChildren,
  AppHistoryRoute: AppHistoryRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPeerRoute: AppPeerRoute,
  AppRecommendationsRoute: AppRecommendationsRoute,
  AppRetestRoute: AppRetestRoute,
  AppTeamsRoute: AppTeamsRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppIndexRoute: AppIndexRoute,
  AppAccountProfileRoute: AppAccountProfileRoute,
  AppAccountSecurityRoute: AppAccountSecurityRoute,
  AppLegalDsrRoute: AppLegalDsrRoute,
  AppSetsSetIdRoute: AppSetsSetIdRoute,
  AppTestsTestIdRoute: AppTestsTestIdRoute,
  AppTestsNewRoute: AppTestsNewRoute,
  AppEduTestsIndexRoute: AppEduTestsIndexRoute,
  AppTestsIndexRoute: AppTestsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SponsorsRouteChildren {
  SponsorsAllRoute: typeof SponsorsAllRoute
  SponsorsIndexRoute: typeof SponsorsIndexRoute
}

const SponsorsRouteChildren: SponsorsRouteChildren = {
  SponsorsAllRoute: SponsorsAllRoute,
  SponsorsIndexRoute: SponsorsIndexRoute,
}

const SponsorsRouteWithChildren = SponsorsRoute._addFileChildren(
  SponsorsRouteChildren,
)

interface DocsAdminRouteChildren {
  DocsAdminSlugRoute: typeof DocsAdminSlugRoute
}

const DocsAdminRouteChildren: DocsAdminRouteChildren = {
  DocsAdminSlugRoute: DocsAdminSlugRoute,
}

const DocsAdminRouteWithChildren = DocsAdminRoute._addFileChildren(
  DocsAdminRouteChildren,
)

interface DocsAppRouteChildren {
  DocsAppSlugRoute: typeof DocsAppSlugRoute
}

const DocsAppRouteChildren: DocsAppRouteChildren = {
  DocsAppSlugRoute: DocsAppSlugRoute,
}

const DocsAppRouteWithChildren =
  DocsAppRoute._addFileChildren(DocsAppRouteChildren)

interface TestBuilderIdResultsRouteChildren {
  TestBuilderIdResultsAttemptIdRoute: typeof TestBuilderIdResultsAttemptIdRoute
}

const TestBuilderIdResultsRouteChildren: TestBuilderIdResultsRouteChildren = {
  TestBuilderIdResultsAttemptIdRoute: TestBuilderIdResultsAttemptIdRoute,
}

const TestBuilderIdResultsRouteWithChildren =
  TestBuilderIdResultsRoute._addFileChildren(TestBuilderIdResultsRouteChildren)

interface TestBuilderIdRouteChildren {
  TestBuilderIdResultsRoute: typeof TestBuilderIdResultsRouteWithChildren
  TestBuilderIdIndexRoute: typeof TestBuilderIdIndexRoute
}

const TestBuilderIdRouteChildren: TestBuilderIdRouteChildren = {
  TestBuilderIdResultsRoute: TestBuilderIdResultsRouteWithChildren,
  TestBuilderIdIndexRoute: TestBuilderIdIndexRoute,
}

const TestBuilderIdRouteWithChildren = TestBuilderIdRoute._addFileChildren(
  TestBuilderIdRouteChildren,
)

interface TestBuilderRouteChildren {
  TestBuilderIdRoute: typeof TestBuilderIdRouteWithChildren
  TestBuilderIndexRoute: typeof TestBuilderIndexRoute
}

const TestBuilderRouteChildren: TestBuilderRouteChildren = {
  TestBuilderIdRoute: TestBuilderIdRouteWithChildren,
  TestBuilderIndexRoute: TestBuilderIndexRoute,
}

const TestBuilderRouteWithChildren = TestBuilderRoute._addFileChildren(
  TestBuilderRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ManageSupportRoute: ManageSupportRoute,
  PrivacyRoute: PrivacyRoute,
  SchoolsRoute: SchoolsRoute,
  SignupRoute: SignupRoute,
  SponsorsRoute: SponsorsRouteWithChildren,
  SupportRoute: SupportRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  BlogSlugRoute: BlogSlugRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  DocsAdminRoute: DocsAdminRouteWithChildren,
  DocsAppRoute: DocsAppRouteWithChildren,
  LoginEnroll2faRoute: LoginEnroll2faRoute,
  LoginVerify2faRoute: LoginVerify2faRoute,
  RShareIdRoute: RShareIdRoute,
  SSlugRoute: SSlugRoute,
  SablonySlugRoute: SablonySlugRoute,
  SchoolsDpaRoute: SchoolsDpaRoute,
  TShareIdRoute: TShareIdRoute,
  TestBuilderRoute: TestBuilderRouteWithChildren,
  TestsSlugRoute: TestsSlugRoute,
  ThankYouSessionIdRoute: ThankYouSessionIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  ContactFormIndexRoute: ContactFormIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  SablonyIndexRoute: SablonyIndexRoute,
  TestIndexRoute: TestIndexRoute,
  TestsIndexRoute: TestsIndexRoute,
  BlogAutorSlugRoute: BlogAutorSlugRoute,
  BlogKategoriaSlugRoute: BlogKategoriaSlugRoute,
  ContactFormTicketIdRoute: ContactFormTicketIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
